---
sidebar: sidebar 
permalink: trident-docker/collect-logs-docker.html 
keywords: deploy, astra trident, trident for docker, docker, logs, binary, managed plugin 
summary: Você pode coletar Registros para obter ajuda com a solução de problemas. O método que você usa para coletar os logs varia de acordo com a forma como você está executando o plugin Docker. 
---
= Recolher registos
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode coletar Registros para obter ajuda com a solução de problemas. O método que você usa para coletar os logs varia de acordo com a forma como você está executando o plugin Docker.



== Recolha registos para resolução de problemas

.Passos
. Se você estiver executando o Astra Trident usando o método de plug-in gerenciado recomendado (ou seja, usando `docker plugin` comandos), visualize-os da seguinte forma:
+
[listing]
----
docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
4fb97d2b956b        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
journalctl -u docker | grep 4fb97d2b956b
----
+
O nível de registo padrão deve permitir diagnosticar a maioria dos problemas. Se você achar que isso não é suficiente, você pode ativar o Registro de depuração.

. Para ativar o registo de depuração, instale o plug-in com o registo de depuração ativado:
+
[listing]
----
docker plugin install netapp/trident-plugin:<version> --alias <alias> debug=true
----
+
Ou, ative o registo de depuração quando o plug-in já estiver instalado:

+
[listing]
----
docker plugin disable <plugin>
docker plugin set <plugin> debug=true
docker plugin enable <plugin>
----
. Se você estiver executando o binário em si no host, os logs estarão disponíveis no diretório do host `/var/log/netappdvp`. Para ativar o registo de depuração, especifique `-debug` quando executar o plugin.




== Dicas gerais de solução de problemas

* O problema mais comum em que novos usuários são executados é uma configuração incorreta que impede que o plugin seja inicializado. Quando isso acontecer, você provavelmente verá uma mensagem como esta quando você tentar instalar ou ativar o plugin:
+
`Error response from daemon: dial unix /run/docker/plugins/<id>/netapp.sock: connect: no such file or directory`

+
Isto significa que o plugin falhou ao iniciar. Felizmente, o plugin foi construído com uma capacidade de Registro abrangente que deve ajudá-lo a diagnosticar a maioria dos problemas que você provavelmente encontrará.

* Se houver problemas com a montagem de um PV em um recipiente, certifique-se de que `rpcbind` está instalado e funcionando. Use o gerenciador de pacotes necessário para o sistema operacional do host e verifique se `rpcbind` está em execução. Você pode verificar o status do serviço rpcbind executando um `systemctl status rpcbind` ou seu equivalente.

