---
sidebar: sidebar 
permalink: faq.html 
keywords: faq, frequently asked questions 
summary: Encontre respostas para as perguntas mais frequentes sobre a instalação, configuração, atualização e solução de problemas do Astra Trident. 
---
= Perguntas frequentes
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Encontre respostas para as perguntas mais frequentes sobre a instalação, configuração, atualização e solução de problemas do Astra Trident.



== Questões gerais



=== Com que frequência o Astra Trident é lançado?

A partir do lançamento de 24,02, o Astra Trident é lançado a cada quatro meses: Fevereiro, junho e outubro.



=== O Astra Trident é compatível com todos os recursos lançados em uma versão específica do Kubernetes?

O Astra Trident geralmente não é compatível com recursos alfa do Kubernetes. O Trident pode oferecer suporte a recursos beta nas duas versões do Trident que seguem a versão beta do Kubernetes.



=== O Astra Trident tem alguma dependência de outros produtos NetApp para seu funcionamento?

O Astra Trident não tem dependências em outros produtos de software NetApp e funciona como uma aplicação autônoma. No entanto, você deve ter um dispositivo de storage de back-end do NetApp.



=== Como posso obter detalhes completos da configuração do Astra Trident?

Use o `tridentctl get` comando para obter mais informações sobre sua configuração do Astra Trident.



=== Posso obter métricas sobre como o storage é provisionado pelo Astra Trident?

Sim. Endpoints Prometheus que podem ser usados para coletar informações sobre a operação do Astra Trident, como o número de backends gerenciados, o número de volumes provisionados, bytes consumidos e assim por diante. Você também pode usar link:https://docs.netapp.com/us-en/cloudinsights/["Cloud Insights"^] para monitoramento e análise.



=== A experiência do usuário muda ao usar o Astra Trident como um supervisor CSI?

Não há alterações no que diz respeito à experiência do usuário e às funcionalidades. O nome do provisionador usado é `csi.trident.netapp.io`. Esse método de instalação do Astra Trident é recomendado se você quiser usar todos os novos recursos fornecidos pelas versões atuais e futuras.



== Instalar e usar o Astra Trident em um cluster Kubernetes



=== O Astra Trident oferece suporte a uma instalação off-line a partir de um Registro privado?

Sim, o Astra Trident pode ser instalado offline. link:../trident-get-started/kubernetes-deploy.html["Saiba mais sobre a instalação do Astra Trident"^]Consulte a .



=== Posso instalar o Astra Trident be remotamente?

Sim. O Astra Trident 18,10 e posterior são compatíveis com a funcionalidade de instalação remota de qualquer máquina que tenha `kubectl` acesso ao cluster. Depois `kubectl` que o acesso for verificado (por exemplo, inicie um `kubectl get nodes` comando da máquina remota para verificar), siga as instruções de instalação.



=== Posso configurar a alta disponibilidade com o Astra Trident?

O Astra Trident é instalado como uma implantação do Kubernetes (ReplicaSet) com uma instância, e por isso tem HA incorporada. Você não deve aumentar o número de réplicas na implantação. Se o nó em que o Astra Trident está instalado for perdido ou o pod estiver inacessível, o Kubernetes reimplanta automaticamente o pod em um nó íntegro no cluster. O Astra Trident é apenas um plano de controle. Portanto, os pods montados atualmente não são afetados se o Astra Trident for reimplantado.



=== O Astra Trident precisa de acesso ao namespace do sistema kube?

O Astra Trident lê o servidor de API Kubernetes para determinar quando as aplicações solicitam novos PVCs de modo que a TI precisa de acesso ao sistema kube.



=== Quais são as funções e Privileges usadas pelo Astra Trident?

O instalador do Trident cria um ClusterRole Kubernetes, que tem acesso específico aos recursos Persistentvolume, PersistentVolumeClaim, StorageClass e segredo do cluster do Kubernetes. link:../trident-get-started/kubernetes-customize-deploy-tridentctl.html["Personalize a instalação do tridentctl"^]Consulte a .



=== Posso gerar localmente os arquivos de manifesto exatos que o Astra Trident usa para instalação?

Você pode gerar e modificar localmente os arquivos de manifesto exatos que o Astra Trident usa para instalação, se necessário. link:trident-get-started/kubernetes-customize-deploy-tridentctl.html["Personalize a instalação do tridentctl"^]Consulte a .



=== Posso compartilhar o mesmo SVM de back-end do ONTAP em duas instâncias separadas do Astra Trident em dois clusters Kubernetes separados?

Embora não seja aconselhado, você pode usar o mesmo SVM de back-end em duas instâncias do Astra Trident. Especifique um nome de volume exclusivo para cada instância durante a instalação e/ou especifique um parâmetro exclusivo `StoragePrefix` no `setup/backend.json` arquivo. Isso serve para garantir que o mesmo FlexVol não seja usado para ambas as instâncias.



=== É possível instalar o Astra Trident sob o ContainerLinux (antigo CoreOS)?

O Astra Trident é simplesmente um pod de Kubernetes e pode ser instalado onde quer que o Kubernetes esteja em execução.



=== Posso usar o Astra Trident com NetApp Cloud Volumes ONTAP?

Sim, o Astra Trident é compatível com AWS, Google Cloud e Azure.



=== O Astra Trident funciona com o Cloud volumes Services?

Sim, o Astra Trident é compatível com o serviço Azure NetApp Files no Azure e com o Cloud Volumes Service no GCP.



== Solução de problemas e suporte



=== O NetApp é compatível com Astra Trident?

Embora o Astra Trident seja de código aberto e fornecido gratuitamente, o NetApp oferece suporte total desde que o back-end do NetApp seja compatível.



=== Como faço para levantar um caso de suporte?

Para levantar um caso de suporte, execute um dos seguintes procedimentos:

. Entre em Contato com seu gerente de conta de suporte e obtenha ajuda para levantar um ticket.
. Envie um caso de suporte entrando em Contato https://www.netapp.com/company/contact-us/support/["Suporte à NetApp"^]com .




=== Como gerar um pacote de log de suporte?

Você pode criar um pacote de suporte executando `tridentctl logs -a`o . Além dos logs capturados no pacote, capture o log do kubelet para diagnosticar os problemas de montagem no lado do Kubernetes. As instruções para obter o log do kubelet variam de acordo com a forma como o Kubernetes é instalado.



=== O que devo fazer se for necessário enviar uma solicitação para um novo recurso?

Crie um problema https://github.com/NetApp/trident["Astra Trident GitHub"^] e mencione *RFE* no assunto e na descrição do problema.



=== Onde posso levantar um defeito?

Crie um problema no https://github.com/NetApp/trident["Astra Trident GitHub"^]. Certifique-se de incluir todas as informações e logs necessários relativos ao problema.



=== O que acontece se eu tiver uma pergunta rápida sobre o Astra Trident sobre a qual preciso de esclarecimentos? Existe uma comunidade ou um fórum?

Se você tiver dúvidas, problemas ou solicitações, entre em Contato conosco através do nosso Astra link:https://discord.gg/NetApp["Canal discord"^] ou GitHub.



=== A senha do meu sistema de storage mudou e o Astra Trident não funciona mais. Como faço para recuperar?

Atualize a senha do backend com `tridentctl update backend myBackend -f </path/to_new_backend.json> -n trident`o . Substitua `myBackend` no exemplo pelo nome do backend e ``/path/to_new_backend.json` pelo caminho para o arquivo correto `backend.json`.



=== O Astra Trident não encontra meu nó Kubernetes. Como faço para corrigir isso?

Há dois cenários prováveis pelos quais o Astra Trident não consegue encontrar um nó Kubernetes. Pode ser devido a um problema de rede no Kubernetes ou a um problema de DNS. O daemonset do nó do Trident que é executado em cada nó do Kubernetes deve ser capaz de se comunicar com o controlador Trident para Registrar o nó no Trident. Se as alterações de rede ocorrerem após a instalação do Astra Trident, você encontrará esse problema apenas com novos nós Kubernetes adicionados ao cluster.



=== Se o pod Trident for destruído, eu perderei os dados?

Os dados não serão perdidos se o pod Trident for destruído. Os metadados do Trident são armazenados em objetos CRD. Todos os PVS que foram provisionados pelo Trident funcionarão normalmente.



== Atualizar o Astra Trident



=== Posso atualizar de uma versão mais antiga diretamente para uma versão mais recente (ignorando algumas versões)?

A NetApp oferece suporte à atualização do Astra Trident de um grande lançamento para o próximo grande lançamento imediato. Você pode atualizar da versão 18.xx para 19.xx, 19.xx para 20.xx, e assim por diante. Você deve testar a atualização em um laboratório antes da implantação da produção.



=== É possível fazer o downgrade do Trident para uma versão anterior?

Se você precisar de uma correção para bugs observados após uma atualização, problemas de dependência ou uma atualização mal sucedida ou incompleta, você deve link:trident-managing-k8s/uninstall-trident.html["Desinstale o Astra Trident"]reinstalar a versão anterior usando as instruções específicas para essa versão. Esta é a única maneira recomendada de fazer o downgrade para uma versão anterior.



== Gerenciar backends e volumes



=== Preciso definir o gerenciamento e LIFs de dados em um arquivo de definição de back-end do ONTAP?

O LIF de gestão é obrigatório. O LIF de dados varia:

* ONTAP SAN: Não especifique para iSCSI. O Astra Trident usa link:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["Mapa de LUN seletivo da ONTAP"^] para descobrir os LIFs iSCI necessários para estabelecer uma sessão de vários caminhos. Um aviso é gerado se `dataLIF` for definido explicitamente. link:trident-use/ontap-san-examples.html["Exemplos e opções de configuração de SAN ONTAP"]Consulte para obter detalhes.
* ONTAP nas: Recomendamos especificar `dataLIF`. Se não for fornecido, o Astra Trident obtém LIFs de dados do SVM. Você pode especificar um nome de domínio totalmente qualificado (FQDN) a ser usado para as operações de montagem NFS, permitindo que você crie um DNS de round-robin para balanceamento de carga em vários LIFs de dados. link:trident-use/ontap-nas-examples.html["Exemplos e opções de configuração do ONTAP nas"]Consulte para obter detalhes




=== O Astra Trident pode configurar o CHAP para backends ONTAP?

Sim. O Astra Trident é compatível com CHAP bidirecional para backends ONTAP. Isso requer configuração `useCHAP=true` em sua configuração de back-end.



=== Como faço para gerenciar políticas de exportação com o Astra Trident?

O Astra Trident pode criar e gerenciar políticas de exportação dinamicamente a partir da versão 20,04. Isso permite que o administrador de storage forneça um ou mais blocos CIDR em sua configuração de back-end e que o Trident adicione IPs de nós que se enquadram nesses intervalos a uma política de exportação criada por ele. Dessa forma, o Astra Trident gerencia automaticamente a adição e exclusão de regras para nós com IPs nos CIDR fornecidos.



=== Os endereços IPv6 podem ser usados para os LIFs de gerenciamento e dados?

O Astra Trident é compatível com a definição de endereços IPv6 para:

* `managementLIF` E `dataLIF` para backends ONTAP nas.
* `managementLIF` Para backends ONTAP SAN. Não é possível especificar `dataLIF` em um back-end de SAN ONTAP.


O Astra Trident deve ser instalado usando o `--use-ipv6` sinalizador ( `tridentctl`para instalação), `IPv6` (para o operador Trident) ou `tridentTPv6` (para instalação Helm) para que ele funcione acima de IPv6.



=== É possível atualizar o LIF de gerenciamento no back-end?

Sim, é possível atualizar o backend Management LIF usando o `tridentctl update backend` comando.



=== É possível atualizar o Data LIF no backend?

Você pode atualizar o Data LIF em `ontap-nas` e `ontap-nas-economy` somente.



=== Posso criar vários back-ends no Astra Trident para Kubernetes?

O Astra Trident pode dar suporte a muitos backends simultaneamente, seja com o mesmo driver ou com drivers diferentes.



=== Como o Astra Trident armazena credenciais de back-end?

O Astra Trident armazena as credenciais de back-end como segredos do Kubernetes.



=== Como o Astra Trident seleciona um back-end específico?

Se os atributos de back-end não puderem ser usados para selecionar automaticamente os pools corretos para uma classe, os `storagePools` parâmetros e `additionalStoragePools` serão usados para selecionar um conjunto específico de pools.



=== Como posso garantir que o Astra Trident não provisione de um back-end específico?

O `excludeStoragePools` parâmetro é usado para filtrar o conjunto de pools que o Astra Trident usará para provisionar e removerá todos os pools correspondentes.



=== Se houver vários backends do mesmo tipo, como o Astra Trident seleciona qual back-end usar?

Se houver vários backends configurados do mesmo tipo, o Astra Trident seleciona o back-end apropriado com base nos parâmetros presentes no `StorageClass` e `PersistentVolumeClaim`no . Por exemplo, se houver vários backends de driver ONTAP-nas, o Astra Trident tentará corresponder parâmetros no `StorageClass` e `PersistentVolumeClaim` combinou e corresponder a um back-end que possa atender aos requisitos listados em `StorageClass` e `PersistentVolumeClaim`. Se houver vários backends que correspondam à solicitação, o Astra Trident seleciona um deles aleatoriamente.



=== O Astra Trident é compatível com CHAP bidirecional com Element/SolidFire?

Sim.



=== Como o Astra Trident implanta Qtrees em um volume ONTAP? Quantos Qtrees podem ser implantados em um único volume?

 `ontap-nas-economy`O driver cria até 200 Qtrees no mesmo FlexVol (configurável entre 50 e 300), 100.000 Qtrees por nó de cluster e 2,4M por cluster. Quando você insere um novo `PersistentVolumeClaim` que é atendido pelo driver de economia, o driver procura ver se já existe um FlexVol que pode atender o novo Qtree. Se o FlexVol não existir que possa servir o Qtree, um novo FlexVol será criado.



=== Como posso definir permissões Unix para volumes provisionados no ONTAP nas?

Você pode definir permissões Unix no volume provisionado pelo Astra Trident definindo um parâmetro no arquivo de definição de back-end.



=== Como posso configurar um conjunto explícito de opções de montagem ONTAP NFS enquanto provisiono um volume?

Por padrão, o Astra Trident não define as opções de montagem como nenhum valor com o Kubernetes. Para especificar as opções de montagem na classe de armazenamento do Kubernetes, siga o exemplo fornecido link:https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-samples/storage-class-ontapnas-k8s1.8-mountoptions.yaml["aqui"^].



=== Como faço para definir os volumes provisionados para uma política de exportação específica?

Para permitir que os hosts apropriados acessem um volume, use o `exportPolicy` parâmetro configurado no arquivo de definição de back-end.



=== Como definir a criptografia de volumes por meio do Astra Trident com ONTAP?

Você pode definir a criptografia no volume provisionado pelo Trident usando o parâmetro de criptografia no arquivo de definição de back-end. Para obter mais informações, consulte: link:trident-reco/security-reco.html#use-astra-trident-with-nve-and-nae["Como o Astra Trident funciona com NVE e NAE"]



=== Qual é a melhor maneira de implementar QoS para ONTAP por meio do Astra Trident?

 `StorageClasses`Use para implementar QoS para ONTAP.



=== Como especificar o provisionamento thin ou thick por meio do Astra Trident?

Os drivers ONTAP oferecem suporte ao provisionamento thin ou thick. Os drivers do ONTAP são padrão para thin Provisioning. Se o provisionamento espesso for desejado, você deverá configurar o arquivo de definição de back-end ou o `StorageClass`. Se ambos estiverem configurados, `StorageClass` tem precedência. Configure o seguinte para o ONTAP:

. On `StorageClass`, defina o `provisioningType` atributo como thick (espesso).
. No arquivo de definição de back-end, ative volumes espessos definindo `backend spaceReserve parameter` como volume.




=== Como posso garantir que os volumes que estão a ser utilizados não sejam eliminados mesmo que elimine acidentalmente o PVC?

A proteção de PVC é ativada automaticamente no Kubernetes a partir da versão 1,10.



=== Posso expandir PVCs de NFS criados pelo Astra Trident?

Sim. Você pode expandir um PVC que foi criado pelo Astra Trident. Observe que o volume com crescimento automático é um recurso do ONTAP que não é aplicável ao Trident.



=== Posso importar um volume enquanto estiver no modo de proteção de dados (DP) da SnapMirror ou offline?

A importação de volume falha se o volume externo estiver no modo DP ou estiver offline. Você recebe a seguinte mensagem de erro:

[listing]
----
Error: could not import volume: volume import failed to get size of volume: volume <name> was not found (400 Bad Request) command terminated with exit code 1.
Make sure to remove the DP mode or put the volume online before importing the volume.
----


=== Como a cota de recursos é traduzida para um cluster NetApp?

A cota de recursos de armazenamento do Kubernetes deve funcionar enquanto o armazenamento do NetApp tiver capacidade. Quando o storage do NetApp não consegue atender às configurações de cota do Kubernetes devido à falta de capacidade, o Astra Trident tenta provisionar, mas faz erros.



=== Posso criar snapshots de volume usando o Astra Trident?

Sim. A criação de snapshots de volume sob demanda e volumes persistentes a partir de snapshots é compatível com o Astra Trident. Para criar PVS a partir de instantâneos, certifique-se de que a `VolumeSnapshotDataSource` porta de recurso foi ativada.



=== Quais são os drivers compatíveis com snapshots de volume Astra Trident?

A partir de hoje, o suporte a snapshot sob demanda está disponível para o nosso `ontap-nas` `ontap-nas-flexgroup` , `ontap-san`, `ontap-san-economy`, , , `solidfire-san` `gcp-cvs`, e `azure-netapp-files` drivers de back-end.



=== Como faço para fazer um backup instantâneo de um volume provisionado pelo Astra Trident com ONTAP?

Isso está disponível nos `ontap-nas` drivers , `ontap-san` e `ontap-nas-flexgroup` . Você também pode especificar um `snapshotPolicy` para o `ontap-san-economy` driver no nível FlexVol.

Isso também está disponível `ontap-nas-economy` nos drivers, mas na granularidade de nível FlexVol e não na granularidade de nível de qtree. Para habilitar a capacidade de snapshot volumes provisionados pelo Astra Trident, defina a opção de parâmetro de back-end `snapshotPolicy` para a política de snapshot desejada, conforme definido no back-end do ONTAP. Todos os snapshots feitos pelo controlador de storage não são conhecidos pelo Astra Trident.



=== Posso definir uma porcentagem de reserva de snapshot para um volume provisionado por meio do Astra Trident?

Sim, você pode reservar uma porcentagem específica de espaço em disco para armazenar as cópias snapshot por meio do Astra Trident definindo `snapshotReserve` o atributo no arquivo de definição de back-end. Se você configurou `snapshotPolicy` e `snapshotReserve` no arquivo de definição de back-end, a porcentagem de reserva de snapshot é definida de acordo com a `snapshotReserve` porcentagem mencionada no arquivo de back-end. Se o `snapshotReserve` número percentual não for mencionado, ONTAP por padrão leva a porcentagem de reserva de snapshot como 5. Se a `snapshotPolicy` opção estiver definida como None (nenhum), a percentagem de reserva de instantâneos é definida como 0.



=== Posso acessar diretamente o diretório instantâneo do volume e copiar arquivos?

Sim, você pode acessar o diretório instantâneo no volume provisionado pelo Trident definindo o `snapshotDir` parâmetro no arquivo de definição de back-end.



=== Posso configurar o SnapMirror para volumes com o Astra Trident?

Atualmente, o SnapMirror precisa ser definido externamente usando a CLI ou o OnCommand System Manager do ONTAP.



=== Como faço para restaurar volumes persistentes para um snapshot específico do ONTAP?

Para restaurar um volume para um instantâneo do ONTAP, execute as seguintes etapas:

. Quiesce o pod do aplicativo que está usando o volume persistente.
. Reverter para o snapshot necessário por meio da CLI ou OnCommand System Manager do ONTAP.
. Reinicie o pod de aplicativos.




=== O Trident provisiona volumes em SVMs que têm um espelhamento de compartilhamento de carga configurado?

Os espelhos de compartilhamento de carga podem ser criados para volumes raiz de SVMs que fornecem dados por NFS. O ONTAP atualiza automaticamente os espelhos de compartilhamento de carga para volumes criados pelo Trident. Isso pode resultar em atrasos nos volumes de montagem. Quando vários volumes são criados usando o Trident, o provisionamento de um volume depende da atualização do espelhamento de compartilhamento de carga do ONTAP.



=== Como posso separar o uso da classe de storage para cada cliente/locatário?

O Kubernetes não permite classes de storage em namespaces. No entanto, você pode usar o Kubernetes para limitar o uso de uma classe de armazenamento específica por namespace usando cotas de recursos de armazenamento, que são por namespace. Para negar acesso a um namespace específico a um armazenamento específico, defina a cota de recurso como 0 para essa classe de armazenamento.
