---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-tridentctl.html 
keywords: upgrade, trident, methods, operator, tridentctl, helm 
summary: 'Pode atualizar facilmente uma instalação existente do Trident utilizando `tridentctl`o .' 
---
= Atualize com o tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode atualizar facilmente uma instalação existente do Trident usando `tridentctl`o .

.Sobre esta tarefa
Desinstalar e reinstalar o Trident funciona como uma atualização. Quando você desinstalar o Trident, a reivindicação de volume persistente (PVC) e o volume persistente (PV) usados pela implantação do Trident não são excluídos. Os PVS que já foram provisionados permanecerão disponíveis enquanto o Trident estiver off-line, e o Trident provisionará volumes para quaisquer PVCs que forem criados no período intermediário depois que ele estiver novamente on-line.

.Antes de começar
Revise link:upgrade-trident.html#select-an-upgrade-method["Selecione um método de atualização"] antes de atualizar usando `tridentctl`o .

.Passos
. Execute o comando uninstall `tridentctl` para remover todos os recursos associados ao Trident, exceto para os CRDs e objetos relacionados.
+
[listing]
----
./tridentctl uninstall -n <namespace>
----
. Reinstale o Trident. link:../trident-get-started/kubernetes-deploy-tridentctl.html["Instale o Trident usando o tridentctl"]Consulte a .



IMPORTANT: Não interrompa o processo de atualização. Certifique-se de que o instalador é executado até a conclusão.
