---
sidebar: sidebar 
permalink: trident-use/create-stor-class.html 
keywords: storage class, manage storage class, storage classes, kubernetes storage classes 
summary: Você pode projetar um arquivo Kubernetes StorageClass e criar o StorageClass para instruir o Astra Trident a provisionar volumes. 
---
= Crie uma classe de armazenamento
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Configure um objeto Kubernetes StorageClass e crie a classe de storage para instruir o Astra Trident a provisionar volumes.



== Configurar um objeto Kubernetes StorageClass

O https://kubernetes.io/docs/concepts/storage/storage-classes/["Objeto Kubernetes StorageClass"^] identifica o Astra Trident como o provisionador que é usado para essa classe e instrui o Astra Trident a provisionar um volume. Por exemplo:

[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: <Name>
provisioner: csi.trident.netapp.io
mountOptions: <Mount Options>
parameters:
  <Trident Parameters>
allowVolumeExpansion: true
volumeBindingMode: Immediate
----
link:../trident-reference/objects.html["Objetos Kubernetes e Trident"]Consulte para obter detalhes sobre como as classes de storage interagem com os `PersistentVolumeClaim` parâmetros e para controlar como o Astra Trident provisiona volumes.



== Crie uma classe de armazenamento

Depois de criar o objeto StorageClass, você pode criar a classe de armazenamento. <<Amostras da classe de armazenamento>> fornece algumas amostras básicas que você pode usar ou modificar.

.Passos
. Esse é um objeto do Kubernetes, então use `kubectl` para criá-lo no Kubernetes.
+
[listing]
----
kubectl create -f sample-input/storage-class-basic-csi.yaml
----
. Agora você deve ver uma classe de storage *Basic-csi* no Kubernetes e Astra Trident, e o Astra Trident deve ter descoberto os pools no back-end.
+
[listing]
----
kubectl get sc basic-csi
NAME         PROVISIONER             AGE
basic-csi    csi.trident.netapp.io   15h

./tridentctl -n trident get storageclass basic-csi -o json
{
  "items": [
    {
      "Config": {
        "version": "1",
        "name": "basic-csi",
        "attributes": {
          "backendType": "ontap-nas"
        },
        "storagePools": null,
        "additionalStoragePools": null
      },
      "storage": {
        "ontapnas_10.0.0.1": [
          "aggr1",
          "aggr2",
          "aggr3",
          "aggr4"
        ]
      }
    }
  ]
}
----




=== Amostras da classe de armazenamento

O Astra Trident https://github.com/NetApp/trident/tree/master/trident-installer/sample-input/storage-class-samples["definições de classe de armazenamento simples para backends específicos"^] fornece .

Alternativamente, você pode editar `sample-input/storage-class-csi.yaml.templ` o arquivo que vem com o instalador e substituir `__BACKEND_TYPE__` pelo nome do driver de armazenamento.

[listing]
----
./tridentctl -n trident get backend
+-------------+----------------+--------------------------------------+--------+---------+
|    NAME     | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------+----------------+--------------------------------------+--------+---------+
| nas-backend | ontap-nas      | 98e19b74-aec7-4a3d-8dcf-128e5033b214 | online |       0 |
+-------------+----------------+--------------------------------------+--------+---------+

cp sample-input/storage-class-csi.yaml.templ sample-input/storage-class-basic-csi.yaml

# Modify __BACKEND_TYPE__ with the storage driver field above (e.g., ontap-nas)
vi sample-input/storage-class-basic-csi.yaml
----