---
sidebar: sidebar 
permalink: trident-use/ontap-san.html 
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Saiba mais sobre como configurar um back-end ONTAP com drivers SAN ONTAP. 
---
= Descrição geral do controlador SAN ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Saiba mais sobre como configurar um back-end ONTAP com drivers SAN ONTAP e Cloud Volumes ONTAP.



== Detalhes do driver SAN ONTAP

O Trident fornece os seguintes drivers de armazenamento SAN para se comunicar com o cluster ONTAP. Os modos de acesso suportados são: _ReadWriteOnce_ (RWO), _ReadOnlyMuy_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2"]
|===
| Condutor | Protocolo | VolumeMode | Modos de acesso suportados | Sistemas de arquivos suportados 


| `ontap-san`  a| 
SCSI iSCSI em FC (pré-visualização técnica no Trident 24,10)
 a| 
Bloco
 a| 
RWO, ROX, RWX, RWOP
 a| 
Sem sistema de arquivos; dispositivo de bloco bruto



| `ontap-san`  a| 
SCSI iSCSI em FC (pré-visualização técnica no Trident 24,10)
 a| 
Sistema de ficheiros
 a| 
RWO, RWOP

ROX e RWX não estão disponíveis no modo de volume do sistema de arquivos.
 a| 
`xfs` `ext3`, , `ext4`



| `ontap-san`  a| 
NVMe/TCP

<<Considerações adicionais para NVMe/TCP>>Consulte a .
 a| 
Bloco
 a| 
RWO, ROX, RWX, RWOP
 a| 
Sem sistema de arquivos; dispositivo de bloco bruto



| `ontap-san`  a| 
NVMe/TCP

<<Considerações adicionais para NVMe/TCP>>Consulte a .
 a| 
Sistema de ficheiros
 a| 
RWO, RWOP

ROX e RWX não estão disponíveis no modo de volume do sistema de arquivos.
 a| 
`xfs` `ext3`, , `ext4`



| `ontap-san-economy`  a| 
ISCSI
 a| 
Bloco
 a| 
RWO, ROX, RWX, RWOP
 a| 
Sem sistema de arquivos; dispositivo de bloco bruto



| `ontap-san-economy`  a| 
ISCSI
 a| 
Sistema de ficheiros
 a| 
RWO, RWOP

ROX e RWX não estão disponíveis no modo de volume do sistema de arquivos.
 a| 
`xfs` `ext3`, , `ext4`

|===
[WARNING]
====
* Use `ontap-san-economy` somente se a contagem de uso de volume persistente for esperada ser maior que link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["Limites de volume ONTAP suportados"^].
* Use `ontap-nas-economy` somente se a contagem de uso de volume persistente for esperada para ser maior do que link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["Limites de volume ONTAP suportados"^] e o `ontap-san-economy` driver não puder ser usado.
* Não use o uso `ontap-nas-economy` se você antecipar a necessidade de proteção de dados, recuperação de desastres ou mobilidade.


====


== Permissões do usuário

O Trident espera ser executado como administrador do ONTAP ou SVM, normalmente usando o `admin` usuário do cluster ou um `vsadmin` usuário SVM, ou um usuário com um nome diferente que tenha a mesma função. Para implantações do Amazon FSX for NetApp ONTAP, o Trident espera ser executado como administrador do ONTAP ou SVM, usando o usuário do cluster `fsxadmin` ou um `vsadmin` usuário SVM, ou um usuário com um nome diferente que tenha a mesma função. O `fsxadmin` usuário é um substituto limitado para o usuário administrador do cluster.


NOTE: Se você usar o `limitAggregateUsage` parâmetro, as permissões de administrador do cluster serão necessárias. Ao usar o Amazon FSX for NetApp ONTAP com Trident, o `limitAggregateUsage` parâmetro não funcionará com as `vsadmin` contas de usuário e `fsxadmin`. A operação de configuração falhará se você especificar este parâmetro.

Embora seja possível criar uma função mais restritiva no ONTAP que um driver Trident pode usar, não recomendamos. A maioria das novas versões do Trident chamarão APIs adicionais que teriam que ser contabilizadas, tornando as atualizações difíceis e suscetíveis a erros.



== Considerações adicionais para NVMe/TCP

O Trident dá suporte ao protocolo NVMe (non-volátil Memory Express) usando `ontap-san` o driver, incluindo:

* IPv6
* Snapshots e clones de volumes NVMe
* Redimensionamento de um volume NVMe
* Importação de um volume NVMe que foi criado fora do Trident para que seu ciclo de vida possa ser gerenciado pelo Trident
* Multipathing nativo NVMe
* Desligamento gracioso ou vergonhoso dos K8s nós (24,06)


O Trident não suporta:

* DH-HMAC-CHAP que é suportado nativamente pelo NVMe
* Multipathing de mapeador de dispositivos (DM)
* Criptografia LUKS

