---
sidebar: sidebar 
permalink: trident-use/trident-fsx-install-trident.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident add-on, Trident EKS add-on, Trident AWS EKS add-on 
summary: 'Usando o Trident com o Amazon FSX for NetApp ONTAP, você pode garantir que os clusters do Kubernetes executados no Amazon Elastic Kubernetes Service (EKS) provisionem volumes persistentes de bloco e arquivo com o respaldo do do ONTAP.' 
---
= Instale o Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Trident simplifica o gerenciamento de armazenamento do Amazon FSX for NetApp ONTAP no Kubernetes para permitir que seus desenvolvedores e administradores se concentrem na implantação de aplicativos.

Você pode instalar o Trident usando um dos seguintes métodos:

* Leme
* Complemento EKS


Se quiser utilizar a funcionalidade de instantâneos, instale o suplemento do controlador de instantâneos CSI. link:https://docs.aws.amazon.com/eks/latest/userguide/csi-snapshot-controller.html["Ativar a funcionalidade de instantâneos para volumes CSI"^]Consulte para obter mais informações.



== Instale o Trident através do leme

[role="tabbed-block"]
====
.Identidade do Pod
--
. Adicione o repositório NetApp Trident à configuração do helm:
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Instale o Trident usando o seguinte exemplo:
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace
----
+
Você pode usar o `helm list` comando para revisar detalhes de instalação, como nome, namespace, gráfico, status, versão do aplicativo e número de revisão.

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2502.0    25.02.0
----


--
.Associação de contas de serviço (IRSA)
--
. Adicione o repositório NetApp Trident à configuração do helm:
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Defina os valores para *provedor de nuvem* e *identidade da nuvem*:
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1  \
--set cloudProvider="AWS" \
--set cloudIdentity="'eks.amazonaws.com/role-arn: arn:aws:iam::<accountID>:role/<AmazonEKS_FSxN_CSI_DriverRole>'" \
--namespace trident \
--create-namespace
----
+
Você pode usar o `helm list` comando para revisar detalhes de instalação, como nome, namespace, gráfico, status, versão do aplicativo e número de revisão.

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2506.0    25.06.0
----


--
====
[NOTE]
====
Se você planeja usar iSCSI, certifique-se de que o iSCSI esteja habilitado na sua máquina cliente. Se estiver usando o sistema operacional AL2023 Worker node, você pode automatizar a instalação do cliente iSCSI adicionando o parâmetro node prep na instalação do helm:

[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace –-set nodePrep={iscsi}
----
====


== Instale o Trident através do suplemento EKS

O complemento do Trident EKS inclui os patches de segurança mais recentes, correções de bugs e é validado pela AWS para funcionar com o Amazon EKS. O complemento EKS permite que você garanta consistentemente que seus clusters do Amazon EKS estejam seguros e estáveis e reduza a quantidade de trabalho que você precisa fazer para instalar, configurar e atualizar complementos.



=== Pré-requisitos

Verifique se você tem o seguinte antes de configurar o complemento do Trident para o AWS EKS:

* Uma conta de cluster do Amazon EKS com assinatura complementar
* Permissões da AWS para o marketplace da AWS:
`"aws-marketplace:ViewSubscriptions",
"aws-marketplace:Subscribe",
"aws-marketplace:Unsubscribe`
* Tipo de AMI: Amazon Linux 2 (AL2_x86_64) ou Amazon Linux 2 ARM(AL2_ARM_64)
* Tipo de nó: AMD ou ARM
* Um sistema de arquivos existente do Amazon FSX for NetApp ONTAP




=== Ative o complemento Trident para AWS

[role="tabbed-block"]
====
.Console de gerenciamento
--
. Abra o console do Amazon EKS em https://console.aws.amazon.com/eks/home#/clusters[].
. No painel de navegação esquerdo, selecione *clusters*.
. Selecione o nome do cluster para o qual deseja configurar o complemento NetApp Trident CSI.
. Selecione *Add-ons* e, em seguida, selecione *Get more add-ons*.
. Siga estas etapas para selecionar o complemento:
+
.. Role para baixo até a seção *Complementos do AWS Marketplace* e digite *"Trident”* na caixa de pesquisa.
.. Marque a caixa de seleção no canto superior direito da caixa Trident by NetApp.
.. Selecione *seguinte*.


. Na página de configurações *Configure Selected add-ons*, faça o seguinte:
+
.. Selecione a *versão* que você gostaria de usar.
.. Se você estiver usando a autenticação IRSA, certifique-se de definir os valores de configuração disponíveis nas Configurações opcionais:
+
*** Selecione a *versão* que você gostaria de usar.
*** Siga o *Esquema de configuração do complemento* e defina o parâmetro *configurationValues* na seção *Valores de configuração* para o role-arn que você criou na etapa anterior (o valor deve estar no seguinte formato):




+
[source, JSON]
----
{

  "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
  "cloudProvider": "AWS"

}
----
+
Se você selecionar Substituir para o método de resolução de conflitos, uma ou mais configurações para o suplemento existente podem ser sobrescritas com as configurações de complemento do Amazon EKS. Se você não ativar essa opção e houver um conflito com suas configurações existentes, a operação falhará. Você pode usar a mensagem de erro resultante para solucionar o conflito. Antes de selecionar essa opção, certifique-se de que o complemento do Amazon EKS não gerencie as configurações que você precisa para gerenciar automaticamente.

. Escolha *seguinte*.
. Na página *Revisão e adição*, escolha *criar*.
+
Depois que a instalação do complemento estiver concluída, você verá o complemento instalado.



--
.CLI DA AWS
--
*1. Crie o  `add-on.json` arquivo*:

*Para Identidade do Pod, use o seguinte formato*:

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
}
----
*Para autenticação IRSA, use o seguinte formato*:

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
  "serviceAccountRoleArn": "<role ARN>",
  "configurationValues": {
    "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
    "cloudProvider": "AWS"
  }
}
----

NOTE: Substitua `<role ARN>` pelo ARN da função criada na etapa anterior.

*2. Instale o complemento Trident EKS.*

[source, console]
----
aws eks create-addon --cli-input-json file://add-on.json
----
--
.eksctl
--
O seguinte comando de exemplo instala o complemento do Trident EKS:

[source, console]
----
eksctl create addon --name netapp_trident-operator --cluster <cluster_name> --force
----
--
====


=== Atualize o complemento Trident EKS

[role="tabbed-block"]
====
.Console de gerenciamento
--
. Abra o console do Amazon EKS https://console.aws.amazon.com/eks/home#/clusters[] .
. No painel de navegação esquerdo, selecione *clusters*.
. Selecione o nome do cluster para o qual deseja atualizar o complemento NetApp Trident CSI.
. Selecione a guia *Complementos*.
. Selecione *Trident by NetApp* e, em seguida, selecione *Edit*.
. Na página *Configurar Trident by NetApp*, faça o seguinte:
+
.. Selecione a *versão* que você gostaria de usar.
.. Expanda *Configurações opcionais de configuração* e modifique conforme necessário.
.. Selecione *Salvar alterações*.




--
.CLI DA AWS
--
O exemplo a seguir atualiza o complemento EKS:

[source, console]
----
aws eks update-addon --cluster-name <eks_cluster_name> --addon-name netapp_trident-operator --addon-version v25.6.0-eksbuild.1 \
  --service-account-role-arn <role-ARN> --resolve-conflict preserve \
  --configuration-values “{\"cloudIdentity\": \"'eks.amazonaws.com/role-arn: <role ARN>'\"}"
----
--
.eksctl
--
* Verifique a versão atual do seu complemento FSxN Trident CSI. Substitua `my-cluster` pelo nome do cluster.
+
[source, console]
----
eksctl get addon --name netapp_trident-operator --cluster my-cluster
----
+
*Exemplo de saída:*



[listing]
----
NAME                        VERSION             STATUS    ISSUES    IAMROLE    UPDATE AVAILABLE    CONFIGURATION VALUES
netapp_trident-operator    v25.6.0-eksbuild.1    ACTIVE    0       {"cloudIdentity":"'eks.amazonaws.com/role-arn: arn:aws:iam::139763910815:role/AmazonEKS_FSXN_CSI_DriverRole'"}
----
* Atualize o complemento para a versão retornada em ATUALIZAÇÃO DISPONÍVEL na saída da etapa anterior.
+
[source, console]
----
eksctl update addon --name netapp_trident-operator --version v25.6.0-eksbuild.1 --cluster my-cluster --force
----


Se você remover `--force` a opção e qualquer uma das configurações de complemento do Amazon EKS entrar em conflito com as configurações existentes, a atualização do complemento do Amazon EKS falhará; você receberá uma mensagem de erro para ajudá-lo a resolver o conflito. Antes de especificar essa opção, verifique se o complemento do Amazon EKS não gerencia as configurações que você precisa gerenciar, pois essas configurações são sobrescritas com essa opção. Para obter mais informações sobre outras opções para essa configuração, link:https://eksctl.io/usage/addons/["Complementos"]consulte . Para obter mais informações sobre o gerenciamento de campo do Amazon EKS Kubernetes, link:https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-field-management.html["Gerenciamento de campo do Kubernetes"]consulte .

--
====


=== Desinstale/remova o complemento Trident EKS

Você tem duas opções para remover um complemento do Amazon EKS:

* *Preserve o software complementar no cluster* – essa opção remove o gerenciamento do Amazon EKS de qualquer configuração. Ele também remove a capacidade do Amazon EKS de notificá-lo de atualizações e atualizar automaticamente o complemento do Amazon EKS depois de iniciar uma atualização. No entanto, ele preserva o software complementar no cluster. Essa opção torna o complemento uma instalação autogerenciada, em vez de um complemento do Amazon EKS. Com essa opção, não há tempo de inatividade para o complemento. Guarde a `--preserve` opção no comando para preservar o complemento.
* *Remover software complementar inteiramente do cluster* – a NetApp recomenda que você remova o complemento do Amazon EKS do cluster somente se não houver recursos no cluster que dependam dele. Remova `--preserve` a opção do `delete` comando para remover o complemento.



NOTE: Se o complemento tiver uma conta do IAM associada a ele, a conta do IAM não será removida.

[role="tabbed-block"]
====
.Console de gerenciamento
--
. Abra o console do Amazon EKS em https://console.aws.amazon.com/eks/home#/clusters[].
. No painel de navegação esquerdo, selecione *clusters*.
. Selecione o nome do cluster para o qual deseja remover o complemento NetApp Trident CSI.
. Selecione a guia *Complementos* e, em seguida, selecione *Trident by NetApp*.*
. Selecione *Remover*.
. Na caixa de diálogo *Remover NetApp_Trident-operator confirmation*, faça o seguinte:
+
.. Se você quiser que o Amazon EKS pare de gerenciar as configurações do complemento, selecione *Preserve on cluster*. Faça isso se quiser manter o software complementar no cluster para que você possa gerenciar todas as configurações do complemento por conta própria.
.. Digite *NetApp_Trident-operator*.
.. Selecione *Remover*.




--
.CLI DA AWS
--
Substitua `my-cluster` pelo nome do cluster e execute o seguinte comando.

[source, console]
----
aws eks delete-addon --cluster-name my-cluster --addon-name netapp_trident-operator --preserve
----
--
.eksctl
--
O seguinte comando desinstala o complemento do Trident EKS:

[source, console]
----
eksctl delete addon --cluster K8s-arm --name netapp_trident-operator
----
--
====