---
sidebar: sidebar 
permalink: trident-use/trident-fsx.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident 
summary: 'Usando o Trident com o Amazon FSX for NetApp ONTAP, você pode garantir que os clusters do Kubernetes executados no Amazon Elastic Kubernetes Service (EKS) provisionem volumes persistentes de bloco e arquivo com o respaldo do do ONTAP.' 
---
= Use o Trident com o Amazon FSX para NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX para NetApp ONTAP"^] É um serviço AWS totalmente gerenciado que permite que os clientes iniciem e executem sistemas de arquivos equipados com o sistema operacional de storage NetApp ONTAP. O FSX para ONTAP permite que você aproveite os recursos, o desempenho e os recursos administrativos do NetApp com os quais você já conhece, ao mesmo tempo em que aproveita a simplicidade, a agilidade, a segurança e a escalabilidade do armazenamento de dados na AWS. O FSX para ONTAP oferece suporte aos recursos do sistema de arquivos ONTAP e APIs de administração.

Você pode integrar o sistema de arquivos do Amazon FSX for NetApp ONTAP ao Trident para garantir que os clusters do Kubernetes executados no Amazon Elastic Kubernetes Service (EKS) possam provisionar volumes persistentes de bloco e arquivo com o respaldo do ONTAP.

Um sistema de arquivos é o principal recurso do Amazon FSX, análogo a um cluster do ONTAP no local. Em cada SVM, você pode criar um ou vários volumes, que são contentores de dados que armazenam os arquivos e pastas em seu sistema de arquivos. Com o Amazon FSX for NetApp ONTAP será fornecido como um sistema de arquivos gerenciado na nuvem. O novo tipo de sistema de arquivos é chamado de *NetApp ONTAP*.

Usando o Trident com o Amazon FSX for NetApp ONTAP, você pode garantir que os clusters do Kubernetes executados no Amazon Elastic Kubernetes Service (EKS) provisionem volumes persistentes de bloco e arquivo com o respaldo do do ONTAP.



== Requisitos

Além link:../trident-get-started/requirements.html["Requisitos da Trident"]do , para integrar o FSX for ONTAP com o Trident, você precisa:

* Um cluster do Amazon EKS existente ou um cluster do Kubernetes autogerenciado com `kubectl` o instalado.
* Um sistema de arquivos e máquina virtual de armazenamento (SVM) do Amazon FSX for NetApp ONTAP que pode ser acessado a partir dos nós de trabalho do seu cluster.
* Nós de trabalho preparados para link:worker-node-prep.html["NFS ou iSCSI"].
+

NOTE: Certifique-se de seguir as etapas de preparação de nós necessárias para o Amazon Linux e https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html["Imagens de máquinas da Amazon"^] Ubuntu (AMIS), dependendo do seu tipo de AMI EKS.





== Considerações

* Volumes SMB:
+
** Os volumes SMB são suportados usando `ontap-nas` apenas o driver.
** Os volumes SMB não são compatíveis com o complemento Trident EKS.
** O Trident dá suporte a volumes SMB montados em pods executados apenas em nós do Windows. link:../trident-use/trident-fsx-storage-backend.html#prepare-to-provision-smb-volumes["Prepare-se para provisionar volumes SMB"]Consulte para obter detalhes.


* Antes do Trident 24,02, os volumes criados nos sistemas de arquivos do Amazon FSX que têm backups automáticos ativados, não puderam ser excluídos pelo Trident. Para evitar esse problema no Trident 24,02 ou posterior, especifique o `fsxFilesystemID`, `apiRegion` AWS , AWS `apikey` e AWS `secretKey` no arquivo de configuração de back-end do AWS FSX for ONTAP.
+

NOTE: Se você estiver especificando uma função do IAM para o Trident, poderá omitir especificar explicitamente os `apiRegion` campos , `apiKey` e `secretKey` para o Trident. Para obter mais informações, link:../trident-use/trident-fsx-examples.html["Opções e exemplos de configuração do FSX for ONTAP"]consulte .





== Autenticação

O Trident oferece dois modos de autenticação.

* Baseado em credenciais (recomendado): Armazena credenciais com segurança no AWS Secrets Manager. Você pode usar o `fsxadmin` usuário do sistema de arquivos ou o `vsadmin` usuário configurado para o SVM.
+

WARNING: O Trident espera ser executado como um `vsadmin` usuário SVM ou como um usuário com um nome diferente que tenha a mesma função. O Amazon FSX for NetApp ONTAP tem um `fsxadmin` usuário que é uma substituição limitada do usuário do cluster do ONTAP `admin`. Recomendamos vivamente a utilização `vsadmin` com o Trident.

* Baseado em certificado: O Trident se comunicará com o SVM em seu sistema de arquivos FSX usando um certificado instalado em seu SVM.


Para obter detalhes sobre como ativar a autenticação, consulte a autenticação do tipo de driver:

* link:ontap-nas-prep.html["Autenticação nas ONTAP"]
* link:ontap-san-prep.html["Autenticação SAN ONTAP"]




== Imagens de máquinas da Amazon testadas (AMIS)

O cluster do EKS é compatível com vários sistemas operacionais, mas a AWS otimizou determinadas AMIS (Amazon Machine Images) para contêineres e EKS. Os AMIS a seguir foram testados com o Trident 24,10.

|===


| AMI | NAS | Economia nas | SAN | SAN-economia 


| AL2023_x86_64_STANDARD | Sim | Sim | Sim | Sim 


| AL2_x86_64 | Sim | Sim | Sim** | Sim** 


| BOTTLEROCKET_x86_64 | Sim* | Sim | N/A. | N/A. 


| AL2023_ARM_64_STANDARD | Sim | Sim | Sim | Sim 


| AL2_ARM_64 | Sim | Sim | Sim** | Sim** 


| BOTTLEROCKET_ARM_64 | Sim* | Sim | N/A. | N/A. 
|===
* *Deve usar "nolock" nas opções de montagem.
* ** Não é possível excluir o PV sem reiniciar o nó



NOTE: Se o seu IAM desejado não está listado aqui, isso não significa que ele não é suportado; simplesmente significa que ele não foi testado. Esta lista serve como um guia para AMIS conhecido por funcionar.

*Testes realizados com*:

* Versão EKS: 1,30
* Método de instalação: Helm e como um suplemento da AWS
* Para nas, tanto o NFSv3 quanto o NFSv4,1 foram testados.
* Para SAN, apenas o iSCSI foi testado, não o NVMe-of.


*Testes realizados*:

* Criar: Classe de armazenamento, pvc, pod
* Excluir: Pod, PVC (regular, qtree/lun – economia, nas com backup da AWS)




== Encontre mais informações

* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Documentação do Amazon FSX para NetApp ONTAP"^]
* https://www.netapp.com/blog/amazon-fsx-for-netapp-ontap/["Blog post no Amazon FSX for NetApp ONTAP"^]

