---
sidebar: sidebar 
permalink: trident-install/kubernetes-deploy-operator.html 
keywords: deploy, Trident, methods, operator, tridentctl, registry, registries 
summary: VocĂȘ pode implantar manualmente o operador Trident para instalar o Trident. Este processo aplica-se a instalaĂ§Ă”es onde as imagens de contentor exigidas pelo Trident nĂŁo sĂŁo armazenadas em um Registro privado. 
---
= Implantar manualmente o operador Trident (modo padrĂŁo)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VocĂȘ pode implantar manualmente o operador Trident para instalar o Trident. Este processo aplica-se a instalaĂ§Ă”es onde as imagens de contentor exigidas pelo Trident nĂŁo sĂŁo armazenadas em um Registro privado. Se tiver um registo de imagens privado, utilize o link:kubernetes-deploy-operator-mirror.html["processo para implantaĂ§ĂŁo off-line"].



== InformaĂ§Ă”es crĂ­ticas sobre Trident 26.02

*VocĂȘ deve ler as seguintes informaĂ§Ă”es crĂ­ticas sobre o Trident.*

.<strong> informaĂ§Ă”es crĂ­ticas sobre o Trident </strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.35 agora Ă© compatĂ­vel com Trident. Atualize Trident antes de atualizar Kubernetes.
* O Trident reforĂ§a estritamente o uso de configuraĂ§ĂŁo multipathing em ambientes SAN, com um valor recomendado de `find_multipaths: no` no arquivo multipath.conf.
+
O uso de configuraĂ§ĂŁo nĂŁo multipathing ou o uso `find_multipaths: yes` de ou `find_multipaths: smart` valor no arquivo multipath.conf resultarĂĄ em falhas de montagem. A Trident recomenda o uso de `find_multipaths: no` desde a versĂŁo 21,07.



=====
====


== Implante manualmente o operador Trident e instale o Trident

Revise link:kubernetes-deploy.html["a visĂŁo geral da instalaĂ§ĂŁo"] para garantir que vocĂȘ atendeu aos prĂ©-requisitos de instalaĂ§ĂŁo e selecionou a opĂ§ĂŁo de instalaĂ§ĂŁo correta para o seu ambiente.

.Antes de comeĂ§ar
Antes de iniciar a instalaĂ§ĂŁo, faĂ§a login no host Linux e verifique se ele estĂĄ gerenciando um trabalho e link:requirements.html["Cluster compatĂ­vel com Kubernetes"^]se vocĂȘ tem o Privileges necessĂĄrio.


NOTE: Com OpenShift, use `oc` em vez de `kubectl` em todos os exemplos que se seguem, e faĂ§a login como *system:admin* primeiro executando `oc login -u system:admin` ou `oc login -u kube-admin`.

[%collapsible%open]
====
. Verifique sua versĂŁo do Kubernetes:
+
[listing]
----
kubectl version
----
. Verifique o Privileges do administrador do cluster:
+
[listing]
----
kubectl auth can-i '*' '*' --all-namespaces
----
. Verifique se vocĂȘ pode iniciar um pod que usa uma imagem do Docker Hub e alcanĂ§ar seu sistema de armazenamento pela rede de pod:
+
[listing]
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----


====


=== Passo 1: Baixe o pacote de instalaĂ§ĂŁo do Trident

O pacote de instalaĂ§ĂŁo do Trident contĂ©m tudo o que vocĂȘ precisa para implantar o operador Trident e instalar o Trident. Baixe e extraia a versĂŁo mais recente do instalador do Trident a partir link:https://github.com/NetApp/trident/releases/latest["A seĂ§ĂŁo _assets_ no GitHub"^]do .

[listing]
----
wget https://github.com/NetApp/trident/releases/download/v26.02.0/trident-installer-26.02.0.tar.gz
tar -xf trident-installer-26.02.0.tar.gz
cd trident-installer
----


=== Passo 2: Crie o `TridentOrchestrator` CRD

Crie o `TridentOrchestrator` DefiniĂ§ĂŁo de Recurso Personalizado (CRD). VocĂȘ criarĂĄ um `TridentOrchestrator` Recurso personalizado mais tarde. Use a versĂŁo CRD YAML apropriada em `deploy/crds` para criar o `TridentOrchestrator` CRD.

[listing]
----
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
----


=== Etapa 3: Implante o operador Trident

O instalador do Trident fornece um arquivo de pacote que pode ser usado para instalar o operador e criar objetos associados. O arquivo bundle Ă© uma maneira fĂĄcil de implantar o operador e instalar o Trident usando uma configuraĂ§ĂŁo padrĂŁo.

* Para clusters que executam o Kubernetes 1,24, `bundle_pre_1_25.yaml` use o .
* Para clusters que executam o Kubernetes 1,25 ou posterior, `bundle_post_1_25.yaml` use o .


.Antes de comeĂ§ar
* Por padrĂŁo, o instalador do Trident implanta o operador no `trident` namespace. Se o `trident` namespace nĂŁo existir, crie-o usando:
+
[listing]
----
kubectl apply -f deploy/namespace.yaml
----
* Para implantar o operador em um namespace diferente do `trident` namespace, atualizar `serviceaccount.yaml` `clusterrolebinding.yaml` `operator.yaml` e gerar o arquivo do pacote usando o `kustomization.yaml`.
+
.. Crie o `kustomization.yaml` usando o seguinte comando onde _<bundle.yaml>_ estĂĄ `bundle_pre_1_25.yaml` ou `bundle_post_1_25.yaml` baseado na sua versĂŁo do Kubernetes.
+
[listing]
----
cp deploy/kustomization_<bundle.yaml> deploy/kustomization.yaml
----
.. Compile o pacote usando o seguinte comando onde _<bundle.yaml>_ estĂĄ `bundle_pre_1_25.yaml` ou `bundle_post_1_25.yaml` baseado na sua versĂŁo do Kubernetes.
+
[listing]
----
kubectl kustomize deploy/ > deploy/<bundle.yaml>
----




.Passos
. Crie os recursos e implante o operador:
+
[listing]
----
kubectl create -f deploy/<bundle.yaml>
----
. Verifique se o operador, a implantaĂ§ĂŁo e as replicasets foram criados.
+
[listing]
----
kubectl get all -n <operator-namespace>
----



IMPORTANT: Deve haver apenas *uma instĂąncia* do operador em um cluster do Kubernetes. NĂŁo crie vĂĄrias implantaĂ§Ă”es do operador Trident.



=== Passo 4: Crie o `TridentOrchestrator` e instale o Trident

Agora vocĂȘ pode criar e instalar o `TridentOrchestrator` Trident. Opcionalmente, vocĂȘ pode link:kubernetes-customize-deploy.html["Personalize a instalaĂ§ĂŁo do Trident"] usar os atributos na `TridentOrchestrator` especificaĂ§ĂŁo.

[listing]
----
kubectl create -f deploy/crds/tridentorchestrator_cr.yaml
tridentorchestrator.trident.netapp.io/trident created

kubectl describe torc trident

Name:        trident
Namespace:
Labels:      <none>
Annotations: <none>
API Version: trident.netapp.io/v1
Kind:        TridentOrchestrator
...
Spec:
  Debug:     true
  Namespace: trident
  nodePrep:
  - iscsi
Status:
  Current Installation Params:
    IPv6:                      false
    Autosupport Hostname:
    Autosupport Image:         netapp/trident-autosupport:26.02
    Autosupport Proxy:
    Autosupport Serial Number:
    Debug:                     true
    Image Pull Secrets:
    Image Registry:
    k8sTimeout:           30
    Kubelet Dir:          /var/lib/kubelet
    Log Format:           text
    Silence Autosupport:  false
    Trident Image:        netapp/trident:26.02.0
  Message:                  Trident installed  Namespace:                trident
  Status:                   Installed
  Version:                  v26.02.0
Events:
    Type Reason Age From Message ---- ------ ---- ---- -------Normal
    Installing 74s trident-operator.netapp.io Installing Trident Normal
    Installed 67s trident-operator.netapp.io Trident installed
----


== Verifique a instalaĂ§ĂŁo

Existem vĂĄrias maneiras de verificar sua instalaĂ§ĂŁo.



===  `TridentOrchestrator`Usando o status

O status de `TridentOrchestrator` indica se a instalaĂ§ĂŁo foi bem-sucedida e exibe a versĂŁo do Trident instalado. Durante a instalaĂ§ĂŁo, o status das `TridentOrchestrator` alteraĂ§Ă”es de `Installing` para `Installed`. Se vocĂȘ observar o `Failed` status e o operador nĂŁo conseguir recuperar sozinho, link:../troubleshooting.html["verifique os logs"].

[cols="2"]
|===
| Estado | DescriĂ§ĂŁo 


| A instalar | O operador estĂĄ a instalar o Trident utilizando este `TridentOrchestrator` CR. 


| Instalado | O Trident foi instalado com sucesso. 


| DesinstalaĂ§ĂŁo | O operador estĂĄ desinstalando o Trident, porque
`spec.uninstall=true`. 


| Desinstalado | O Trident Ă© desinstalado. 


| Falha | O operador nĂŁo pĂŽde instalar, corrigir, atualizar ou desinstalar o Trident; o operador tentarĂĄ recuperar automaticamente deste estado. Se este estado persistir, serĂĄ necessĂĄrio resolver o problema. 


| A atualizar | O operador estĂĄ atualizando uma instalaĂ§ĂŁo existente. 


| Erro | O `TridentOrchestrator` nĂŁo Ă© utilizado. Outro jĂĄ existe. 
|===


=== Usando o status de criaĂ§ĂŁo do pod

VocĂȘ pode confirmar se a instalaĂ§ĂŁo do Trident foi concluĂ­da revisando o status dos pods criados:

[listing]
----
kubectl get pods -n trident

NAME                                       READY   STATUS    RESTARTS   AGE
trident-controller-7d466bf5c7-v4cpw        6/6     Running   0           1m
trident-node-linux-mr6zc                   2/2     Running   0           1m
trident-node-linux-xrp7w                   2/2     Running   0           1m
trident-node-linux-zh2jt                   2/2     Running   0           1m
trident-operator-766f7b8658-ldzsv          1/1     Running   0           3m
----


=== UtilizaĂ§ĂŁo `tridentctl`

VocĂȘ pode usar `tridentctl` para verificar a versĂŁo do Trident instalada.

[listing]
----
./tridentctl -n trident version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 26.02.0        | 26.02.0        |
+----------------+----------------+
----