---
sidebar: sidebar 
permalink: trident-protect/learn-about-trident-protect.html 
keywords: overview, concepts, features, use case, workloads, how workload factory works 
summary: O Trident Protect permite que você proteja seus aplicativos e dados de aplicativos usando o Trident. 
---
= Saiba mais sobre o Trident Protect.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O NetApp Trident Protect oferece recursos avançados de gerenciamento de dados de aplicativos que aprimoram a funcionalidade e a disponibilidade de aplicativos Kubernetes com estado, com suporte dos sistemas de armazenamento NetApp ONTAP e do provisionador de armazenamento NetApp Trident CSI.  O Trident Protect simplifica o gerenciamento, a proteção e a movimentação de cargas de trabalho conteinerizadas em nuvens públicas e ambientes locais. Ele também oferece recursos de automação por meio de sua API e CLI.

Você pode proteger aplicativos com o Trident Protect criando recursos personalizados (CRs) ou usando a CLI do Trident Protect.



== O que se segue?

Você pode consultar os requisitos do Trident Protect antes de instalá-lo:

* link:trident-protect-requirements.html["Requisitos do Trident Protect"]

