---
sidebar: sidebar 
permalink: trident-protect/trident-protect-upgrade.html 
keywords: trident, protect, netapp, upgrade, new, version 
summary: Você pode atualizar o Trident Protect para a versão mais recente para aproveitar os novos recursos ou correções de bugs. 
---
= Aprimore o Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode atualizar o Trident Protect para a versão mais recente para aproveitar os novos recursos ou correções de bugs.

[NOTE]
====
* Ao atualizar a partir da versão 24.10, os snapshots executados durante a atualização podem falhar. Essa falha não impede a criação de snapshots futuros, sejam eles manuais ou agendados. Se um snapshot falhar durante a atualização, você pode criar um novo snapshot manualmente para garantir a proteção do seu aplicativo.
+
Para evitar possíveis falhas, você pode desabilitar todos os agendamentos de snapshots antes da atualização e reabilitá-los posteriormente. No entanto, isso resultará na perda de snapshots agendados durante o período de atualização.

* Para instalações em registros privados, certifique-se de que o gráfico Helm e as imagens necessárias para a versão desejada estejam disponíveis em seu registro privado e verifique se seus valores Helm personalizados são compatíveis com a nova versão do gráfico. Para obter mais informações, consultelink:trident-protect-installation.html["Instale o Trident Protect a partir de um registro privado."] .


====


== Passo 1: Selecione uma versão

As versões do Trident Protect seguem uma convenção de nomenclatura baseada em datas `YY.MM`, onde "YY" são os dois últimos dígitos do ano e "MM" é o mês. As versões com ponto seguem uma `YY.MM.X` convenção, onde "X" é o nível de patch. Você selecionará a versão para atualizar com base na versão da qual está atualizando.

* Você pode realizar uma atualização direta para qualquer versão de destino que esteja dentro de um intervalo de quatro versões da sua versão instalada. Por exemplo, você pode atualizar diretamente de 24.10 (ou qualquer versão secundária de 24.10) para 25.10.
* Se você estiver atualizando de uma versão fora do período de quatro versões, execute uma atualização em várias etapas. Use as instruções de atualização para a link:../earlier-versions.html["versão anterior"] da qual você está atualizando para atualizar para a versão mais recente que se encaixe no período de quatro versões. Por exemplo, se você estiver executando 24.10 e quiser atualizar para 26.02:
+
.. Primeira atualização da 24.10 para a 25.02.
.. Em seguida, atualize de 25.02 para 26.02.






== Etapa 2: atualize Trident Protect

Para atualizar o Trident Protect, siga os passos abaixo.

.Passos
. Atualize o repositório Helm do Trident:
+
[source, console]
----
helm repo update
----
. Atualize os CRDs do Trident Protect:
+

NOTE: Esta etapa é necessária se você estiver atualizando de uma versão anterior à 25.06, pois os CRDs agora estão incluídos no gráfico Helm do Trident Protect.

+
.. Execute este comando para mudar o gerenciamento de CRDs de  `trident-protect-crds` para  `trident-protect` :
+
[source, console]
----
kubectl get crd | grep protect.trident.netapp.io | awk '{print $1}' | xargs -I {} kubectl patch crd {} --type merge -p '{"metadata":{"annotations":{"meta.helm.sh/release-name": "trident-protect"}}}'
----
.. Execute este comando para excluir o segredo do Helm para o  `trident-protect-crds` gráfico:
+

NOTE: Não desinstale o  `trident-protect-crds` gráfico usando o Helm, pois isso pode remover seus CRDs e quaisquer dados relacionados.

+
[source, console]
----
kubectl delete secret -n trident-protect -l name=trident-protect-crds,owner=helm
----


. Aprimore o Trident Protect:
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect --version 100.2602.0 --namespace trident-protect
----
+

NOTE: Você pode configurar o nível de registro durante a atualização adicionando `--set logLevel=debug` ao comando de atualização. O nível de registro padrão é `warn` . O registro de depuração é recomendado para a resolução de problemas, pois ajuda o suporte da NetApp a diagnosticar problemas sem exigir alterações no nível de registro ou reprodução do problema.


