---
sidebar: sidebar 
permalink: trident-protect/trident-protect-installation.html 
keywords: install, trident, protect, requirements, registry 
summary: Se o seu ambiente atender aos requisitos, você pode seguir estas etapas para instalar o Trident Protect. 
---
= Instale e configure o Trident Protect.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se o seu ambiente atender aos requisitos do Trident Protect, você pode seguir estas etapas para instalar o Trident Protect em seu cluster.  Você pode obter o Trident Protect da NetApp ou instalá-lo a partir do seu próprio registro privado. A instalação a partir de um registro privado é útil caso seu cluster não tenha acesso à Internet.



== Instale o Trident Protect

[role="tabbed-block"]
====
.Instale o Trident Protect da NetApp.
--
.Passos
. Adicione o repositório Helm do Trident:
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Use o Helm para instalar o Trident Protect. Substituir `<name-of-cluster>` com um nome de cluster, que será atribuído ao cluster e usado para identificar os backups e snapshots do cluster:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --version 100.2510.0 --create-namespace --namespace trident-protect
----
. Opcionalmente, para ativar o registro de depuração (recomendado para resolução de problemas), use:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --set logLevel=debug --version 100.2510.0 --create-namespace --namespace trident-protect
----
+
O registro de depuração ajuda o suporte da NetApp a solucionar problemas sem exigir alterações no nível de registro ou reprodução do problema.



--
.Instale o Trident Protect a partir de um registro privado.
--
Você pode instalar o Trident Protect a partir de um registro de imagens privado caso seu cluster Kubernetes não tenha acesso à Internet. Nestes exemplos, substitua os valores entre colchetes por informações do seu ambiente:

.Passos
. Puxe as seguintes imagens para a sua máquina local, atualize as etiquetas e, em seguida, envie-as para o seu registo privado:
+
[source, console]
----
docker.io/netapp/controller:25.10.0
docker.io/netapp/restic:25.10.0
docker.io/netapp/kopia:25.10.0
docker.io/netapp/kopiablockrestore:25.10.0
docker.io/netapp/trident-autosupport:25.10.0
docker.io/netapp/exechook:25.10.0
docker.io/netapp/resourcebackup:25.10.0
docker.io/netapp/resourcerestore:25.10.0
docker.io/netapp/resourcedelete:25.10.0
docker.io/netapp/trident-protect-utils:v1.0.0
----
+
Por exemplo:

+
[source, console]
----
docker pull docker.io/netapp/controller:25.10.0
----
+
[source, console]
----
docker tag docker.io/netapp/controller:25.10.0 <private-registry-url>/controller:25.10.0
----
+
[source, console]
----
docker push <private-registry-url>/controller:25.10.0
----
+

NOTE: Para obter o gráfico Helm, primeiro faça o download do gráfico Helm em um computador com acesso à internet usando `helm pull trident-protect --version 100.2510.0 --repo https://netapp.github.io/trident-protect-helm-chart`Em seguida, copie o resultado. `trident-protect-100.2510.0.tgz` copie o arquivo para seu ambiente offline e instale-o usando `helm install trident-protect ./trident-protect-100.2510.0.tgz` em vez da referência ao repositório na etapa final.

. Crie o namespace do sistema Trident Protect:
+
[source, console]
----
kubectl create ns trident-protect
----
. Inicie sessão no registo:
+
[source, console]
----
helm registry login <private-registry-url> -u <account-id> -p <api-token>
----
. Crie um segredo para usar para autenticação de Registro privado:
+
[source, console]
----
kubectl create secret docker-registry regcred --docker-username=<registry-username> --docker-password=<api-token> -n trident-protect --docker-server=<private-registry-url>
----
. Adicione o repositório Helm do Trident:
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Crie um arquivo chamado `protectValues.yaml` . Certifique-se de que contenha as seguintes configurações do Trident Protect:
+
[source, yaml]
----
---
imageRegistry: <private-registry-url>
imagePullSecrets:
  - name: regcred
----
+

NOTE: O `imageRegistry` e `imagePullSecrets` Os valores se aplicam a todas as imagens componentes, incluindo `resourcebackup` e `resourcerestore` . Se você enviar imagens para um caminho de repositório específico dentro do seu registro (por exemplo, `example.com:443/my-repo`), inclua o caminho completo no campo de registro. Isso garantirá que todas as imagens sejam extraídas de `<private-registry-url>/<image-name>:<tag>`.

. Use o Helm para instalar o Trident Protect. Substituir `<name_of_cluster>` com um nome de cluster, que será atribuído ao cluster e usado para identificar os backups e snapshots do cluster:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name_of_cluster> --version 100.2510.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----
. Opcionalmente, para ativar o registro de depuração (recomendado para resolução de problemas), use:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --set logLevel=debug --version 100.2510.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----
+
O registro de depuração ajuda o suporte da NetApp a solucionar problemas sem exigir alterações no nível de registro ou reprodução do problema.



--
====

NOTE: Para opções adicionais de configuração do gráfico Helm, incluindo configurações de AutoSupport e filtragem de namespace, consulte link:trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["Personalize a instalação do Trident Protect"].
