---
sidebar: sidebar 
permalink: trident-protect/trident-protect-kubevirt-vms.html 
keywords: kubevirt, openshift virtualization, virtual machine, vm, backup, restore, includedvirtualmachines 
summary: Proteja mĂĄquinas virtuais KubeVirt em OpenShift Virtualization com Trident Protect. FaĂ§a backup de todas as VMs em um namespace ou direcione VMs especĂ­ficas pelo nome. Restaure seletivamente VMs individuais de um backup ou de um arquivo de snapshot. 
---
= Proteja mĂĄquinas virtuais KubeVirt com Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Trident Protect permite que vocĂȘ faĂ§a backup e restaure mĂĄquinas virtuais (VMs) KubeVirt em execuĂ§ĂŁo na VirtualizaĂ§ĂŁo OpenShift. VocĂȘ pode proteger todas as VMs em um ou mais namespaces de uma vez, ou usar o campo  `includedVirtualMachines` para selecionar VMs especĂ­ficas pelo nome. Trident Protect coleta automaticamente todos os recursos dependentes da VM durante o backup e, durante a restauraĂ§ĂŁo, vocĂȘ pode recuperar todo o arquivo ou restaurar VMs individualmente.



== KubeVirt modos de proteĂ§ĂŁo

Trident Protect oferece duas maneiras de definir quais KubeVirt VMs proteger. Escolha um modo ao definir um aplicativo:

[cols="1,1,2"]
|===
| Modo | Campo | DescriĂ§ĂŁo 


| Baseado em namespace | `includedNamespaces` | Proteja todos os recursos correspondentes em um ou mais namespaces. Use um `labelSelector` na entrada do namespace para controlar quais VMs serĂŁo incluĂ­das dinamicamente. 


| Com escopo de VM | `includedVirtualMachines` | Proteja mĂĄquinas virtuais KubeVirt especĂ­ficas por namespace e nome. Use este modo quando as mĂĄquinas virtuais estiverem distribuĂ­das por namespaces ou quando vocĂȘ nĂŁo quiser proteger todos os recursos de um namespace. 
|===
VocĂȘ deve especificar exatamente um campo (`includedNamespaces` ou  `includedVirtualMachines`) no  `ApplicationSpec`. VocĂȘ nĂŁo pode usar ambos na mesma aplicaĂ§ĂŁo.

Ambos os modos suportam filtragem adicional:

* Use  `resourceFilter` para incluir ou excluir recursos especĂ­ficos.
* Use  `includedClusterScopedResources` para incluir recursos compatĂ­veis com escopo de cluster, como  `StorageClass` objetos.



NOTE: Trident Protect pode congelar e descongelar os sistemas de arquivos de mĂĄquinas virtuais KubeVirt durante operaĂ§Ă”es de proteĂ§ĂŁo de dados para garantir a consistĂȘncia. Para detalhes de configuraĂ§ĂŁo, consulte link:trident-protect-requirements.html#protecting-data-with-kubevirt-vms["ProteĂ§ĂŁo de dados com mĂĄquinas virtuais do KubeVirt"].



== Recursos coletados durante backup e snapshot

Ao criar um backup ou snapshot para um aplicativo que inclui KubeVirt VMs, Trident Protect coleta os recursos de VM selecionados e descobre automaticamente seus recursos dependentes.

O comportamento de coleta se aplica em dois casos:

* AplicaĂ§Ă”es com escopo de VM que usam  `includedVirtualMachines`.
* AplicaĂ§Ă”es baseadas em namespaces que contĂȘm KubeVirt `VirtualMachine` recursos.




=== ColeĂ§ĂŁo com escopo de VM

Para aplicaĂ§Ă”es com escopo de mĂĄquina virtual (VM), Trident Protect inicia com cada  `VirtualMachine` listada em  `includedVirtualMachines` e descobre os recursos dependentes necessĂĄrios para restaurar essa VM.

[cols="1,1,3"]
|===
| Tipo de recurso | Escopo | Como Ă© descoberto 


| `VirtualMachine` | Com namespace | CorrespondĂȘncia direta da lista  `includedVirtualMachines`. 


| `VirtualMachineInstance` | Com namespace | Mesmo namespace e nome da VM, se a VM estiver em execuĂ§ĂŁo. 


| `VirtualMachineInstancetype` | Com namespace | Referenciado por `spec.instancetype` quando `kind: VirtualMachineInstancetype`. 


| `VirtualMachineClusterInstancetype` | Cluster | Referenciado por  `spec.instancetype` quando  `kind` nĂŁo estĂĄ definido ou  `kind: VirtualMachineClusterInstancetype`. 


| `VirtualMachinePreference` | Com namespace | Referenciado por  `spec.preference` quando  `kind: VirtualMachinePreference`. 


| `VirtualMachineClusterPreference` | Cluster | Referenciado por  `spec.preference` quando  `kind` nĂŁo estĂĄ definido ou  `kind: VirtualMachineClusterPreference`. 


| `DataVolume` | Com namespace | Referenciado por  `spec.template.spec.volumes[].dataVolume.name`. 


| `PersistentVolumeClaim` | Com namespace | Descoberto a partir de PVCs de suporte de DataVolume, que usam o mesmo nome que o DataVolume; referĂȘncias diretas de PVC em  `persistentVolumeClaim.claimName`; PVCs de despejo de memĂłria em  `memoryDump.claimName`; e PVCs efĂȘmeros em  `ephemeral.persistentVolumeClaim.claimName`. 


| `PersistentVolume` | Cluster | Descoberto a partir do PV de suporte para cada PVC coletado usando  `spec.volumeName`. 


| `Secret` | Com namespace | Descoberto a partir de segredos de volume em  `secret.secretName`; segredos de extraĂ§ĂŁo de imagem containerDisk; referĂȘncias a segredos de dados do usuĂĄrio e de rede CloudInitNoCloud e CloudInitConfigDrive; segredos Sysprep; segredos de extraĂ§ĂŁo de imagem de contĂȘiner KernelBoot; e segredos de SSH ou senha AccessCredentials. 


| `ConfigMap` | Com namespace | Descoberto a partir do volume ConfigMaps em  `configMap.name` e Sysprep ConfigMaps. 


| `ServiceAccount` | Com namespace | Descoberto a partir de  `serviceAccount.serviceAccountName`referĂȘncias de volume. 


| `NetworkAttachmentDefinition` | Com namespace | Descoberto em redes Multus  `spec.template.spec.networks[].multus.networkName` quando o nome da rede nĂŁo contĂ©m  `/`. Somente referĂȘncias NetworkAttachmentDefinition do mesmo namespace sĂŁo coletadas. ReferĂȘncias entre namespaces diferentes sĂŁo ignoradas. 


| `Pod` | Com namespace | Descoberto para  `virt-launcher`Pods usando o seletor de rĂłtulos `kubevirt.io=virt-launcher,vm.kubevirt.io/name=<vmName>`. 


| Classe de armazenamento, volumes Trident e backends Trident | Cluster | Coletados da mesma forma que os aplicativos baseados em namespace, com base nos PVCs descobertos para a VM. 
|===

NOTE: ApĂłs a coleta de todos os recursos com escopo de mĂĄquina virtual e namespace, Trident Protect aplica o padrĂŁo `resourceFilter`, caso esteja configurado. A coleta de recursos com escopo de cluster prossegue normalmente.



=== ColeĂ§ĂŁo baseada em namespace

Para aplicaĂ§Ă”es baseadas em namespaces, Trident Protect examina os namespaces selecionados e coleta todos os recursos correspondentes. Se algum KubeVirt `VirtualMachine` objeto for encontrado, Trident Protect coleta automaticamente seus recursos dependentes, incluindo tipos de instĂąncia, preferĂȘncias e `virt-launcher` Pods, da mesma forma que faz para aplicaĂ§Ă”es com escopo de mĂĄquina virtual.

Isso significa que os recursos especĂ­ficos da VM sĂŁo incluĂ­dos no seu backup ou snapshot mesmo quando o aplicativo Ă© definido com  `includedNamespaces`.



== Proteja mĂĄquinas virtuais usando definiĂ§Ă”es de aplicativos baseadas em namespace

Ao criar um aplicativo baseado em namespaces, Trident Protect examina os namespaces selecionados e coleta todos os recursos, incluindo quaisquer KubeVirt VMs. Para cada mĂĄquina virtual encontrada, Trident Protect tambĂ©m coleta os recursos dependentes necessĂĄrios para fazer backup e restaurar essa mĂĄquina virtual.

Exemplo de CR de aplicaĂ§ĂŁo baseada em namespace:

[source, yaml]
----
apiVersion: protect.trident.netapp.io/v1
kind: Application
metadata:
  name: <application_name>
  namespace: <application_namespace>
spec:
  includedNamespaces:
    - namespace: <vm_namespace>
----
ApĂłs criar o aplicativo, use os fluxos de trabalho padrĂŁo do Trident Protect para backups e snapshots:

* Para exemplos de snapshots em YAML, veja link:trident-protect-protect-apps.html#create-an-on-demand-snapshot["Crie um snapshot sob demanda"].
* Para exemplos de YAML de backup, consulte link:trident-protect-protect-apps.html#create-an-on-demand-backup["Crie um backup sob demanda"].




=== Comportamento de restauraĂ§ĂŁo para aplicativos de mĂĄquina virtual baseados em namespace

Como os aplicativos baseados em namespaces coletam recursos dos namespaces selecionados, o backup ou snapshot pode incluir objetos de tempo de execuĂ§ĂŁo do KubeVirt e metadados gerenciados pelo KubeVirt. Alguns desses objetos nĂŁo devem ser restaurados diretamente porque representam o estado de tempo de execuĂ§ĂŁo do cluster de origem.

Durante a restauraĂ§ĂŁo, Trident Protect aplica transformaĂ§Ă”es compatĂ­veis com KubeVirt para remover os metadados do cluster de origem e ignorar recursos transitĂłrios do KubeVirt. Isso ajuda o KubeVirt a recriar a mĂĄquina virtual corretamente no ambiente restaurado.

[cols="1,2"]
|===
| Recurso | Transformar 


| VirtualMachine | Remove rĂłtulos e anotaĂ§Ă”es que comeĂ§am com  `kubevirt.io/`. 


| VirtualMachineInstance | Remove rĂłtulos e anotaĂ§Ă”es que comeĂ§am com  `kubevirt.io/`. 


| VirtualMachineInstanceMigration | Ignorado e nĂŁo restaurado. 


| VirtualMachineSnapshot | Ignorado e nĂŁo restaurado. 


| VirtualMachineSnapshotContent | Ignorado e nĂŁo restaurado. 


| Pod (`virt-launcher`) | Ignorado quando o pod possui o  `kubevirt.io=virt-launcher` rĂłtulo. 
|===

NOTE: Trident Protect restaura os recursos do KubeVirt em uma ordem definida para evitar problemas de dependĂȘncia. CDI DataVolumes (`cdi.kubevirt.io` sĂŁo restaurados primeiro para que os dados de disco da mĂĄquina virtual estejam disponĂ­veis antes da criaĂ§ĂŁo dos objetos da mĂĄquina virtual. Depois disso, VirtualMachines (`kubevirt.io` sĂŁo restauradas antes de VirtualMachineInstances.



== ProteĂ§ĂŁo dinĂąmica de VM com seletores de rĂłtulos

Se vocĂȘ deseja proteger mĂĄquinas virtuais dinamicamente sem listar o nome de cada mĂĄquina virtual, use definiĂ§Ă”es de aplicativos baseadas em namespace com seletores de rĂłtulo.

Apenas o VirtualMachine CR precisa de rĂłtulos. Recursos dependentes, como DataVolumes, PVCs, Segredos e ConfigMaps, sĂŁo coletados automaticamente.

.Passos
. Rotule as CRs da mĂĄquina virtual com um rĂłtulo compartilhado:
+
[source, console]
----
kubectl label virtualmachine <vm_name 1> app=<label_value> -n <vm_namespace>
kubectl label virtualmachine <vm_name_2> app=<label_value> -n <vm_namespace>
----
. Crie um CR de aplicativo com  `includedNamespaces` e um  `labelSelector`:
+
[source, yaml]
----
apiVersion: protect.trident.netapp.io/v1
kind: Application
metadata:
  name: <application_name>
  namespace: <application_namespace>
spec:
  includedNamespaces:
    - namespace: <vm_namespace>
      labelSelector:
        matchLabels:
          app: <label_value>
----
. Crie backups e restauraĂ§Ă”es usando o fluxo de trabalho padrĂŁo do Trident Protect.


*Detalhes adicionais*:

* VocĂȘ pode adicionar ou remover VMs da proteĂ§ĂŁo a qualquer momento alterando os rĂłtulos:


[source, console]
----
kubectl label virtualmachine <vm_name_to_add> app=<label_value> -n <vm_namespace>
kubectl label virtualmachine <vm_name_to_remove> app=<different_label_value> -n <vm_namespace>
----
* VocĂȘ tambĂ©m pode usar seletores de rĂłtulo em vĂĄrios namespaces:


[source, yaml]
----
spec:
  includedNamespaces:
    - namespace: <vm_namespace_1>
      labelSelector:
        matchLabels:
          <label_key>: <label_value>
    - namespace: <vm_namespace_2>
      labelSelector:
        matchLabels:
          <label_key>: <label_value>
----


== Proteja VMs especĂ­ficas com includedVirtualMachines

Use  `includedVirtualMachines` quando vocĂȘ quiser proteger um conjunto nomeado de VirtualMachines em um ou mais namespaces e restaurar seletivamente VMs especĂ­ficas de um arquivamento.

Tanto a solicitaĂ§ĂŁo de alteraĂ§ĂŁo (CR) quanto a restauraĂ§ĂŁo utilizam o mesmo formato de seletor  `includedVirtualMachines`.

Utilize este seletor em diferentes contextos:

* Em um CR de aplicaĂ§ĂŁo, ele define quais VMs estĂŁo protegidas.
* Em uma solicitaĂ§ĂŁo de restauraĂ§ĂŁo (CR), define quais mĂĄquinas virtuais (VMs) sĂŁo restauradas a partir do backup ou do arquivamento de Snapshot.



NOTE: Na restauraĂ§ĂŁo de CRs, `includedVirtualMachines` Ă© opcional. Se vocĂȘ nĂŁo incluir este campo, todo o arquivamento serĂĄ restaurado. Quando especificado, somente as VMs listadas e seus recursos dependentes serĂŁo restaurados.

O YAML abaixo mostra a estrutura do seletor compartilhado:

[source, yaml]
----
includedVirtualMachines:
  - namespace: <vm_namespace_1>
    names:
      - <vm_name_1>
      - <vm_name_2>
  - namespace: <vm_namespace_2>
    names:
      - <vm_name_3>
----

NOTE: VĂĄrias entradas em `includedVirtualMachines` podem referenciar namespaces diferentes, o que possibilita definiĂ§Ă”es e restauraĂ§Ă”es de aplicativos com reconhecimento de mĂĄquina virtual em mĂșltiplos namespaces.

[cols="1,1,2"]
|===
| Campo | Tipo | DescriĂ§ĂŁo 


| namespace | cadeia de carateres | Namespace do Kubernetes que contĂ©m os objetos da mĂĄquina virtual de destino. 


| nomes | lista de strings | Um ou mais nomes de mĂĄquinas virtuais nesse namespace. 
|===
.Exemplo de aplicaĂ§ĂŁo baseada em mĂĄquina virtual:
[source, yaml]
----
apiVersion: protect.trident.netapp.io/v1
kind: Application
metadata:
  name: <application_name>
  namespace: <application_namespace>
spec:
  includedVirtualMachines:
    - namespace: <vm_namespace_1>
      names:
        - <vm_name_1>
        - <vm_name_2>
    - namespace: <vm_namespace_2>
      names:
        - <vm_name_3>
  includedClusterScopedResources:
    - group: storage.k8s.io
      kind: StorageClass
----


== Restaurar VMs especĂ­ficas do KubeVirt

VocĂȘ pode usar  `includedVirtualMachines` em CRs de restauraĂ§ĂŁo para restaurar apenas as KubeVirt VMs selecionadas de um backup, Snapshot ou arquivamento de Snapshot replicado.

Quando  `includedVirtualMachines` Ă© especificado em um CR de restauraĂ§ĂŁo, Trident Protect restaura apenas as VirtualMachines listadas e seus recursos dependentes, como  `VirtualMachineInstance`, `DataVolume`, `PersistentVolumeClaim`, `PersistentVolume`, `Secret`, `ConfigMap`, `ServiceAccount` e outros objetos relacionados Ă  mĂĄquina virtual.

Se vocĂȘ nĂŁo especificar  `includedVirtualMachines`na CR de restauraĂ§ĂŁo, o Trident Protect restaura o arquivamento completo de acordo com a configuraĂ§ĂŁo da CR de restauraĂ§ĂŁo.



=== CRs de restauraĂ§ĂŁo e comandos CLI compatĂ­veis

A tabela a seguir lista os CRs de restauraĂ§ĂŁo compatĂ­veis  `includedVirtualMachines` e seus respectivos comandos da CLI.

[cols="1,1,3"]
|===
| Restaurar CR | Comando CLI | DescriĂ§ĂŁo 


| `BackupRestore` | `tridentctl-protect create backuprestore` | Restaura a partir de um backup para mapeamentos de namespace novos ou diferentes. Suporta  `namespaceMapping`e  `storageClassMapping`. 


| `BackupInplaceRestore` | `tridentctl-protect create backupinplacerestore` | Restaura a partir de um backup no namespace ou namespaces originais. 


| `SnapshotRestore` | `tridentctl-protect create snapshotrestore` | Restaura a partir de um snapshot para mapeamentos de namespace novos ou diferentes. Suporta  `namespaceMapping` e  `storageClassMapping`. 


| `SnapshotInplaceRestore` | `tridentctl-protect create snapshotinplacerestore` | Restaura a partir de um Snapshot no namespace ou namespaces originais. 


| `ReplicateSnapshotRestore` | Somente YAML ou use o comando CLI compatĂ­vel se disponĂ­vel em seu ambiente | Restaura a partir de um snapshot replicado. Suporta  `namespaceMapping`,  `storageClassMapping` e restauraĂ§ĂŁo no local usando a flag  `inPlaceRestore`. 
|===

NOTE: A  `tridentctl-protect`CLI nĂŁo possui uma flag para  `includedVirtualMachines`em comandos de restauraĂ§ĂŁo. Para restaurar VMs especĂ­ficas, vocĂȘ deve aplicar um arquivo YAML de restauraĂ§ĂŁo CR diretamente usando  `kubectl apply`. VocĂȘ pode escrever o YAML do zero ou usar a CLI com  `--dry-run --output yaml`para gerar um arquivo inicial, adicionar o campo  `includedVirtualMachines` em  `spec`, e entĂŁo aplicĂĄ-lo.



=== Comportamento de restauraĂ§ĂŁo com escopo de VM

O campo  `includedVirtualMachines` em um CR de restauraĂ§ĂŁo usa o mesmo formato de seletor que o CR do aplicativo:

[source, yaml]
----
includedVirtualMachines:
  - namespace: <source_vm_namespace>
    names:
      - <vm_name_1>
      - <vm_name_2>
----
Para CRs de restauraĂ§ĂŁo, os valores de namespace  `includedVirtualMachines` referem-se aos namespaces de origem conforme existem no backup, Snapshot ou arquivamento de Snapshot replicado.

Se vocĂȘ usar  `namespaceMapping`, o Trident Protect primeiro seleciona as mĂĄquinas virtuais solicitadas do arquivamento de origem e, em seguida, aplica os mapeamentos de namespace durante a restauraĂ§ĂŁo. Se vocĂȘ usar  `storageClassMapping`, o Trident Protect aplica os mapeamentos de classe de armazenamento durante a fase de transformaĂ§ĂŁo da restauraĂ§ĂŁo.



=== Gerar YAML de restauraĂ§ĂŁo com a CLI

VocĂȘ pode usar  `tridentctl-protect` para gerar um CR de restauraĂ§ĂŁo base e, em seguida, editar o YAML para adicionar  `includedVirtualMachines`.

[source, console]
----
tridentctl-protect create <restore_command> <restore_name> \
  <restore_options> \
  --dry-run --output yaml > <restore_name>.yaml
----
Edite o arquivo YAML gerado e adicione o campo  `includedVirtualMachines` em  `spec`, depois aplique o arquivo:

[source, console]
----
kubectl apply -f <restore_name>.yaml
----


=== Exemplo: defina um aplicativo baseado em mĂĄquina virtual

O seguinte aplicativo protege trĂȘs mĂĄquinas virtuais especĂ­ficas em dois namespaces.

[source, yaml]
----
apiVersion: protect.trident.netapp.io/v1
kind: Application
metadata:
  name: production-vms
  namespace: prod
spec:
  includedVirtualMachines:
    - namespace: prod
      names:
        - app-server
        - database-server
    - namespace: monitoring
      names:
        - prometheus-vm
  includedClusterScopedResources:
    - group: storage.k8s.io
      kind: StorageClass
----


=== Exemplo: criar um backup

A criaĂ§ĂŁo de um backup para um aplicativo baseado em mĂĄquina virtual utiliza o backup CR padrĂŁo. NĂŁo sĂŁo necessĂĄrios campos especĂ­ficos de mĂĄquina virtual no backup CR.

[source, yaml]
----
apiVersion: protect.trident.netapp.io/v1
kind: Backup
metadata:
  name: daily-backup
  namespace: prod
spec:
  applicationRef: production-vms
  appVaultRef: s3-vault
----


=== Exemplo: restaurar uma Ășnica mĂĄquina virtual a partir de um backup

O exemplo a seguir restaura apenas  `database-server` do arquivamento de backup. As outras VMs no arquivamento, como  `app-server` e  `prometheus-vm`, sĂŁo ignoradas.

[source, yaml]
----
apiVersion: protect.trident.netapp.io/v1
kind: BackupRestore
metadata:
  name: restore-db-only
  namespace: prod-vms-restore
spec:
  appVaultRef: s3-vault
  appArchivePath: backups/production-vms/2026-03-10T00-00-00Z
  namespaceMapping:
    - source: prod
      destination: prod-dr
  includedVirtualMachines:
    - namespace: prod
      names:
        - database-server
----
[source, console]
----
kubectl apply -f restore-db-only.yaml
----
Somente  `database-server` e seus recursos dependentes, como DataVolumes, PVCs, PVs, Secrets, ConfigMaps e recursos relacionados do KubeVirt, sĂŁo restaurados.



=== Exemplo: restaurar uma Ășnica mĂĄquina virtual no local a partir de um backup

O exemplo a seguir restaura apenas  `database-server`no namespace original a partir do arquivamento de backup.

[source, yaml]
----
apiVersion: protect.trident.netapp.io/v1
kind: BackupInplaceRestore
metadata:
  name: ipr-db-only
  namespace: prod
spec:
  appVaultRef: s3-vault
  appArchivePath: backups/production-vms/2026-03-10T00-00-00Z
  includedVirtualMachines:
    - namespace: prod
      names:
        - database-server
----
[source, console]
----
kubectl apply -f ipr-db-only.yaml
----


=== Exemplo: restaurar uma Ășnica mĂĄquina virtual a partir de um Snapshot

O exemplo a seguir restaura apenas  `ubuntu-vm-blue-a627be38` de um arquivamento de Snapshot.

[source, yaml]
----
apiVersion: protect.trident.netapp.io/v1
kind: SnapshotRestore
metadata:
  name: blue-vm-snap-restore
  namespace: blue
spec:
  appVaultRef: my-appvault
  appArchivePath: snapshots/protectctl-blue-vm/snap-1
  includedVirtualMachines:
    - namespace: blue
      names:
        - ubuntu-vm-blue-a627be38
----
[source, console]
----
kubectl apply -f blue-vm-snap-restore.yaml
----


=== Combine a restauraĂ§ĂŁo da mĂĄquina virtual com outros filtros

VocĂȘ pode usar  `includedVirtualMachines` junto com  `resourceFilter`,  `namespaceMapping` e  `storageClassMapping` no mesmo CR de restauraĂ§ĂŁo para ajustar com precisĂŁo o que serĂĄ restaurado.

Ao adicionar um  `resourceFilter`, Trident Protect primeiro seleciona as VMs listadas em  `includedVirtualMachines` e seus recursos dependentes. Em seguida, aplica o filtro de recursos para restringir ainda mais o que estĂĄ incluĂ­do ou excluĂ­do desses resultados.

[source, yaml]
----
spec:
  includedVirtualMachines:
    - namespace: <vm_namespace>
      names:
        - <vm_name>
  resourceFilter:
    resourceSelectionCriteria: Include
    resourceMatchers:
      - kinds: ["PersistentVolumeClaim"]
        names: ["<pvc_name>"]
----
Para  `BackupRestore`,  `SnapshotRestore` e  `ReplicateSnapshotRestore`,  `namespaceMapping` e  `storageClassMapping` funcionam junto com  `includedVirtualMachines`. As referĂȘncias de namespace em  `includedVirtualMachines` correspondem aos namespaces de origem conforme aparecem no arquivamento. Os mapeamentos de namespace e classe de armazenamento sĂŁo aplicados durante a fase de transformaĂ§ĂŁo de restauraĂ§ĂŁo apĂłs a conclusĂŁo da filtragem.

Para obter detalhes sobre o comportamento de restauraĂ§ĂŁo, consulte link:trident-protect-restore-apps.html["Restaure aplicativos usando o Trident Protect."].



== Crie um aplicativo com escopo de mĂĄquina virtual usando a CLI

Use a  `--virtual-machines` flag para restringir o escopo de um aplicativo a KubeVirt VMs especĂ­ficas em vez de namespaces inteiros. A  `--virtual-machines` flag Ă© mutuamente exclusiva com  `--namespaces`.

.Passos
. Crie a aplicaĂ§ĂŁo executando um dos seguintes comandos, substituindo os valores entre colchetes pelas informaĂ§Ă”es do seu ambiente. O formato para o  `--virtual-machines` parĂąmetro Ă©  `<namespace>(<vm_name>)`. Para vĂĄrias VMs, use nomes separados por vĂ­rgulas dentro dos parĂȘnteses:
+
** Uma Ășnica mĂĄquina virtual em um namespace:
+
[source, console]
----
tridentctl-protect create application <application_name> \
  -n <application_namespace> \
  --virtual-machines "<vm_namespace>(<vm_name>)"
----
** MĂșltiplas mĂĄquinas virtuais em diferentes namespaces:
+
[source, console]
----
tridentctl-protect create application <application_name> \
  -n <application_namespace> \
  --virtual-machines "<vm_namespace_1>(<vm_name_1>,<vm_name_2>),<vm_namespace_2>(<vm_name_3>)"
----






== InformaĂ§Ă”es relacionadas

* link:trident-protect-manage-applications.html["Definir uma aplicaĂ§ĂŁo para gestĂŁo"]
* link:trident-protect-protect-apps.html["Proteger aplicaĂ§Ă”es"]
* link:trident-protect-restore-apps.html["Restaure aplicativos usando o Trident Protect."]
* link:trident-protect-restore-settings.html["Use as configuraĂ§Ă”es avanĂ§adas de restauraĂ§ĂŁo"]
* link:trident-protect-cli.html["Instale o plugin Trident Protect CLI"]
* link:trident-protect-appvault-custom-resources.html["Use objetos AppVault para gerenciar buckets"]

