---
sidebar: sidebar 
permalink: trident-protect/trident-protect-generate-support-bundle.html 
keywords: trident, protect, bundle, support, netapp, custom, resource, file 
summary: 'O Trident Protect permite que os administradores gerem pacotes que incluem informações úteis ao suporte da NetApp, incluindo logs, métricas e informações de topologia sobre os clusters e aplicativos em gerenciamento. Se você estiver conetado à Internet, poderá fazer upload de pacotes de suporte para o site de suporte da NetApp (NSS) usando um arquivo de recurso personalizado (CR).' 
---
= Gerar um pacote de suporte Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O Trident Protect permite que os administradores gerem pacotes que incluem informações úteis ao suporte da NetApp, incluindo logs, métricas e informações de topologia sobre os clusters e aplicativos em gerenciamento. Se você estiver conetado à Internet, poderá fazer upload de pacotes de suporte para o site de suporte da NetApp (NSS) usando um arquivo de recurso personalizado (CR).

[role="tabbed-block"]
====
.Crie um pacote de suporte usando um CR
--
.Passos
. Crie o arquivo de recurso personalizado (CR) e nomeie-o (por exemplo, `trident-protect-support-bundle.yaml` ).
. Configure os seguintes atributos:
+
** *metadata.name*: (_required_) o nome deste recurso personalizado; escolha um nome único e sensível para o seu ambiente.
** *Spec.triggerType*: (_required_) determina se o pacote de suporte é gerado imediatamente ou programado. A geração de pacotes programados acontece às 12AM UTC. Valores possíveis:
+
*** Programado
*** Manual


** *Spec.uploadEnabled*: (_Optional_) controla se o pacote de suporte deve ser carregado para o site de suporte da NetApp depois que ele é gerado. Se não for especificado, o padrão é `false`. Valores possíveis:
+
*** verdadeiro
*** falso (padrão)


** *Spec.dataWindowStart*: (_Optional_) Uma cadeia de carateres de data no formato RFC 3339 que especifica a data e a hora em que a janela de dados incluídos no pacote de suporte deve começar. Se não for especificado, o padrão é 24 horas atrás. A data da janela mais antiga que você pode especificar é de 7 dias atrás.
+
Exemplo YAML:

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: AutoSupportBundle
metadata:
  name: trident-protect-support-bundle
spec:
  triggerType: Manual
  uploadEnabled: true
  dataWindowStart: 2024-05-05T12:30:00Z
----


. Depois de preencher o `astra-support-bundle.yaml` ficheiro com os valores corretos, aplique o CR:
+
[source, console]
----
kubectl apply -f trident-protect-support-bundle.yaml
----


--
.Crie um pacote de suporte usando a CLI
--
.Passos
. Crie o pacote de suporte, substituindo valores entre parênteses por informações do seu ambiente. O `trigger-type` determina se o pacote é criado imediatamente ou se o tempo de criação é ditado pelo agendamento e pode ser `Manual` ou `Scheduled`. A predefinição é `Manual`.
+
Por exemplo:

+
[source, console]
----
tridentctl-protect create autosupportbundle <my_bundle_name> --trigger-type <trigger_type>
----


--
====