---
sidebar: sidebar 
permalink: trident-protect/trident-protect-customize-installation.html 
keywords: customize, trident protect, resource limits, security context constraints, SCC, NetApp AutoSupport, proxy connection, helm, helm chart, helm upgrade 
summary: Personalize as configurações padrão do Trident Protect para atender às suas necessidades específicas. 
---
= Personalize a instalação do Trident Protect
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode personalizar a configuração padrão do Trident Protect para atender aos requisitos específicos do seu ambiente.



== Especifique os limites de recursos do contêiner Trident Protect.

Você pode usar um arquivo de configuração para especificar limites de recursos para os contêineres do Trident Protect após a instalação do Trident Protect.  A definição de limites de recursos permite controlar a quantidade de recursos do cluster que são consumidos pelas operações do Trident Protect.

.Passos
. Crie um arquivo chamado `resourceLimits.yaml`.
. Preencha o arquivo com as opções de limite de recursos para os contêineres do Trident Protect de acordo com as necessidades do seu ambiente.
+
O seguinte exemplo de arquivo de configuração mostra as configurações disponíveis e contém os valores padrão para cada limite de recursos:

+
[source, yaml]
----
---
jobResources:
  defaults:
    limits:
      cpu: 8000m
      memory: 10000Mi
      ephemeralStorage: ""
    requests:
      cpu: 100m
      memory: 100Mi
      ephemeralStorage: ""
  resticVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  resticVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
----
. Aplique os valores do `resourceLimits.yaml` arquivo:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f resourceLimits.yaml --reuse-values
----




== Personalizar restrições de contexto de segurança

Você pode usar um arquivo de configuração para modificar as restrições de contexto de segurança (SCCs) do OpenShift para contêineres Trident Protect após instalar o Trident Protect. Essas restrições definem as limitações de segurança para os pods em um cluster Red Hat OpenShift.

.Passos
. Crie um arquivo chamado `sccconfig.yaml`.
. Adicione a opção SCC ao arquivo e modifique os parâmetros de acordo com as necessidades do seu ambiente.
+
O exemplo a seguir mostra os valores padrão dos parâmetros para a opção SCC:

+
[source, yaml]
----
scc:
  create: true
  name: trident-protect-job
  priority: 1
----
+
Esta tabela descreve os parâmetros para a opção SCC:

+
|===
| Parâmetro | Descrição | Padrão 


| criar | Determina se um recurso SCC pode ser criado. Um recurso SCC será criado somente se `scc.create` estiver definido como `true` e o processo de instalação Helm identificar um ambiente OpenShift. Se não estiver operando no OpenShift, ou se `scc.create` estiver definido como `false`, nenhum recurso SCC será criado. | verdadeiro 


| nome | Especifica o nome do SCC. | Trident-protect-job 


| prioridade | Define a prioridade do SCC. Os SCCs com valores de prioridade mais elevados são avaliados antes daqueles com valores mais baixos. | 1 
|===
. Aplique os valores do `sccconfig.yaml` arquivo:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f sccconfig.yaml --reuse-values
----
+
Isso substituirá os valores padrão pelos especificados no `sccconfig.yaml` arquivo.





== Configure as definições adicionais do gráfico de navegação do Trident Protect.

Você pode personalizar as configurações do AutoSupport e a filtragem de namespace para atender aos seus requisitos específicos.  A tabela a seguir descreve os parâmetros de configuração disponíveis:

|===
| Parâmetro | Tipo | Descrição 


| autoSupport.proxy | cadeia de carateres | Configura um URL de proxy para conexões do NetApp AutoSupport .  Use isso para rotear uploads de pacotes de suporte por meio de um servidor proxy.  Exemplo: `http://my.proxy.url` . 


| autoSupport.inseguro | booleano | Ignora a verificação TLS para conexões proxy AutoSupport quando definido como `true` .  Use somente para conexões proxy inseguras.  (padrão: `false` ) 


| autoSupport.habilitado | booleano | Ativa ou desativa os uploads diários do pacote Trident Protect AutoSupport . Quando definido para `false` Os uploads diários agendados estão desativados, mas você ainda pode gerar pacotes de suporte manualmente. (padrão: `true` ) 


| restaurarSkipNamespaceAnnotations | cadeia de carateres | Lista separada por vírgulas de anotações de namespace a serem excluídas das operações de backup e restauração.  Permite filtrar namespaces com base em anotações. 


| restaurarIgnorarEtiquetasDeEspaçoDeNomes | cadeia de carateres | Lista separada por vírgulas de rótulos de namespace a serem excluídos das operações de backup e restauração.  Permite filtrar namespaces com base em rótulos. 
|===
Você pode configurar essas opções usando um arquivo de configuração YAML ou sinalizadores de linha de comando:

[role="tabbed-block"]
====
.Usar arquivo YAML
--
.Passos
. Crie um arquivo de configuração e nomeie-o `values.yaml` .
. No arquivo que você criou, adicione as opções de configuração que deseja personalizar.
+
[source, console]
----
autoSupport:
  enabled: false
  proxy: http://my.proxy.url
  insecure: true
restoreSkipNamespaceAnnotations: "annotation1,annotation2"
restoreSkipNamespaceLabels: "label1,label2"
----
. Depois de preencher o `values.yaml` arquivo com os valores corretos, aplique o arquivo de configuração:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f values.yaml --reuse-values
----


--
.Usar sinalizador CLI
--
.Passos
. Use o seguinte comando com o `--set` sinalizador para especificar parâmetros individuais:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect \
  --set autoSupport.enabled=false \
  --set autoSupport.proxy=http://my.proxy.url \
  --set-string restoreSkipNamespaceAnnotations="{annotation1,annotation2}" \
  --set-string restoreSkipNamespaceLabels="{label1,label2}" \
  --reuse-values
----


--
====


== Restrinja os pods do Trident Protect a nós específicos.

Você pode usar a restrição de seleção de nós `nodeSelector` do Kubernetes para controlar quais de seus nós são elegíveis para executar pods do Trident Protect, com base nos rótulos dos nós.  Por padrão, o Trident Protect é restrito a nós que executam Linux. Você pode personalizar ainda mais essas restrições de acordo com suas necessidades.

.Passos
. Crie um arquivo chamado `nodeSelectorConfig.yaml`.
. Adicione a opção nodeSeletor ao arquivo e modifique o arquivo para adicionar ou alterar rótulos de nó para restringir de acordo com as necessidades do seu ambiente. Por exemplo, o arquivo a seguir contém a restrição padrão do sistema operacional, mas também tem como alvo uma região específica e nome do aplicativo:
+
[source, yaml]
----
nodeSelector:
  kubernetes.io/os: linux
  region: us-west
  app.kubernetes.io/name: mysql
----
. Aplique os valores do `nodeSelectorConfig.yaml` arquivo:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f nodeSelectorConfig.yaml --reuse-values
----
+
Isso substitui as restrições padrão com as que você especificou no `nodeSelectorConfig.yaml` arquivo.


