---
sidebar: sidebar 
permalink: trident-protect/trident-protect-installation.html 
keywords: install, trident, protect, requirements, registry 
summary: Se o seu ambiente atender aos requisitos, siga estas etapas para instalar o Trident Protect. 
---
= Instalar e configurar o Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se o seu ambiente atender aos requisitos do Trident Protect, siga estas etapas para instalar o Trident Protect no cluster. Você pode obter o Trident Protect do NetApp, ou instalá-lo a partir de seu próprio Registro privado. A instalação a partir de um registo privado é útil se o cluster não conseguir aceder à Internet.



== Instale o Trident Protect

[role="tabbed-block"]
====
.Instale o Trident Protect do NetApp
--
.Passos
. Adicione o repositório Helm do Trident:
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Use o Helm para instalar o Trident Protect. Substitua `<name-of-cluster>` por um nome de cluster, que será atribuído ao cluster e usado para identificar os backups e snapshots do cluster:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --version 100.2506.0 --create-namespace --namespace trident-protect
----


--
.Instale o Trident Protect a partir de um registo privado
--
Você pode instalar o Trident Protect a partir de um Registro de imagem privado se o cluster do Kubernetes não conseguir acessar a Internet. Nestes exemplos, substitua valores entre parênteses por informações do seu ambiente:

.Passos
. Puxe as seguintes imagens para a sua máquina local, atualize as etiquetas e, em seguida, envie-as para o seu registo privado:
+
[source, console]
----
docker.io/netapp/controller:25.06.0
docker.io/netapp/restic:25.06.0
docker.io/netapp/kopia:25.06.0
docker.io/netapp/kopiablockrestore:25.06.0
docker.io/netapp/trident-autosupport:25.06.0
docker.io/netapp/exechook:25.06.0
docker.io/netapp/resourcebackup:25.06.0
docker.io/netapp/resourcerestore:25.06.0
docker.io/netapp/resourcedelete:25.06.0
docker.io/bitnami/kubectl:1.30.2
gcr.io/kubebuilder/kube-rbac-proxy:v0.16.0
----
+
Por exemplo:

+
[source, console]
----
docker pull docker.io/netapp/controller:25.06.0
----
+
[source, console]
----
docker tag docker.io/netapp/controller:25.06.0 <private-registry-url>/controller:25.06.0
----
+
[source, console]
----
docker push <private-registry-url>/controller:25.06.0
----
+

NOTE: Para obter o gráfico Helm, primeiro faça o download do gráfico Helm em um computador com acesso à internet usando `helm pull trident-protect --version 100.2506.0 --repo https://netapp.github.io/trident-protect-helm-chart`Em seguida, copie o resultado. `trident-protect-100.2506.0.tgz` copie o arquivo para seu ambiente offline e instale-o usando `helm install trident-protect ./trident-protect-100.2506.0.tgz` em vez da referência ao repositório na etapa final.

. Crie o namespace do sistema Trident Protect:
+
[source, console]
----
kubectl create ns trident-protect
----
. Inicie sessão no registo:
+
[source, console]
----
helm registry login <private-registry-url> -u <account-id> -p <api-token>
----
. Crie um segredo para usar para autenticação de Registro privado:
+
[source, console]
----
kubectl create secret docker-registry regcred --docker-username=<registry-username> --docker-password=<api-token> -n trident-protect --docker-server=<private-registry-url>
----
. Adicione o repositório Helm do Trident:
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Crie um arquivo chamado `protectValues.yaml`. Verifique se ele contém as seguintes configurações de proteção Trident:
+
[source, yaml]
----
---
controller:
  image:
    registry: <private-registry-url>
rbacProxy:
  image:
    registry: <private-registry-url>
crCleanup:
  imagePullSecrets:
    - name: regcred
webhooksCleanup:
  imagePullSecrets:
    - name: regcred
----
+

NOTE: O `controller.image.registry` Essa configuração se aplica a todas as imagens componentes, incluindo `resourcebackup` e `resourcerestore`. Se você enviar imagens para um caminho de repositório específico dentro do seu registro (por exemplo, `example.com:443/my-repo`), inclua o caminho completo no campo de registro. Isso garantirá que todas as imagens sejam extraídas de `<private-registry-url>/<image-name>:<tag>`.

. Use o Helm para instalar o Trident Protect. Substitua `<name_of_cluster>` por um nome de cluster, que será atribuído ao cluster e usado para identificar os backups e snapshots do cluster:
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name_of_cluster> --version 100.2506.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----


--
====

NOTE: Para opções adicionais de configuração do gráfico Helm, incluindo configurações de AutoSupport e filtragem de namespace, consulte link:trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["Personalize a instalação do Trident Protect"].
